export interface AcademyTopic {
  id: string;
  title: { en: string; he: string };
  category: 'fundamentals' | 'technology' | 'economics' | 'regulatory' | 'operations';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  estimatedMinutes: number;
  icon: string;
  summary: { en: string; he: string };
  content: { en: string[]; he: string[] };
  keyPoints: { en: string[]; he: string[] };
  practicalTips: { en: string[]; he: string[] };
  argentinaContext?: { en: string; he: string };
}

export const academyTopics: AcademyTopic[] = [
  {
    id: 'what-is-solar',
    title: { en: 'What Is Solar Energy?', he: 'מהי אנרגיה סולארית?' },
    category: 'fundamentals',
    difficulty: 'beginner',
    estimatedMinutes: 10,
    icon: 'Sun',
    summary: {
      en: 'Understand how sunlight becomes electricity through the photovoltaic effect.',
      he: 'הבינו כיצד אור השמש הופך לחשמל באמצעות האפקט הפוטו-וולטאי.',
    },
    content: {
      en: [
        'Solar energy works by converting sunlight directly into electricity using photovoltaic (PV) cells. When photons from sunlight strike a solar cell made of semiconductor material (usually silicon), they knock electrons loose from their atoms. This movement of electrons creates an electrical current — this is called the photovoltaic effect, first discovered by Edmond Becquerel in 1839.',
        'A single solar cell produces only about 0.5 volts, so multiple cells are wired together to form a solar panel (or module), typically producing 30-50 volts. The electricity generated by solar panels is direct current (DC), but homes and businesses use alternating current (AC). An inverter converts DC to AC so the electricity can power your appliances or be fed into the grid.',
        'Solar energy systems have no moving parts, require minimal maintenance, and can last 25-30 years. The amount of electricity generated depends on sunlight intensity (irradiance), panel angle, temperature, and shading. Argentina receives between 1,400 and 2,200 kWh/m² of solar irradiance per year, making most of the country highly suitable for solar installations.',
      ],
      he: [
        'אנרגיה סולארית פועלת על ידי המרת אור שמש ישירות לחשמל באמצעות תאים פוטו-וולטאיים (PV). כאשר פוטונים מאור השמש פוגעים בתא סולארי העשוי מחומר מוליך למחצה (בדרך כלל סיליקון), הם משחררים אלקטרונים מהאטומים שלהם. תנועה זו של אלקטרונים יוצרת זרם חשמלי — תופעה זו נקראת האפקט הפוטו-וולטאי, שהתגלה לראשונה על ידי אדמון בקרל ב-1839.',
        'תא סולארי בודד מייצר כ-0.5 וולט בלבד, ולכן מספר תאים מחוברים יחד ליצירת פאנל סולארי (או מודול), שמייצר בדרך כלל 30-50 וולט. החשמל שמייצרים הפאנלים הוא זרם ישר (DC), אך בתים ועסקים משתמשים בזרם חילופין (AC). ממיר (אינוורטר) הופך את הזרם הישר לזרם חילופין כדי שהחשמל יוכל להפעיל מכשירי חשמל או להיזרק לרשת.',
        'למערכות סולאריות אין חלקים נעים, הן דורשות תחזוקה מינימלית ויכולות להחזיק 25-30 שנה. כמות החשמל המיוצרת תלויה בעוצמת אור השמש (הקרנה), זווית הפאנל, טמפרטורה והצללה. ארגנטינה מקבלת בין 1,400 ל-2,200 קוט"ש/מ"ר של הקרנה סולארית בשנה, מה שהופך את רוב המדינה למתאימה מאוד להתקנות סולאריות.',
      ],
    },
    keyPoints: {
      en: [
        'The photovoltaic effect converts sunlight directly into DC electricity using silicon semiconductor cells',
        'Solar panels are made of many cells wired together to produce usable voltage (30-50V per panel)',
        'An inverter is required to convert DC from panels to AC used by appliances and the grid',
        'Solar systems have no moving parts and typically last 25-30 years with minimal maintenance',
        'Output depends on irradiance, panel orientation, temperature, and shading conditions',
      ],
      he: [
        'האפקט הפוטו-וולטאי ממיר אור שמש ישירות לחשמל DC באמצעות תאי סיליקון מוליכים למחצה',
        'פאנלים סולאריים מורכבים ממספר תאים המחוברים יחד לייצור מתח שמיש (30-50V לפאנל)',
        'נדרש אינוורטר להמרת זרם ישר מהפאנלים לזרם חילופין המשמש מכשירי חשמל והרשת',
        'למערכות סולאריות אין חלקים נעים והן מחזיקות בדרך כלל 25-30 שנה עם תחזוקה מינימלית',
        'התפוקה תלויה בהקרנה, כיוון הפאנל, טמפרטורה ותנאי הצללה',
      ],
    },
    practicalTips: {
      en: [
        'Start by checking your electricity bill to understand your monthly consumption in kWh — this is the basis for any solar system design',
        'Use free tools like Google Earth or SunCalc to get a rough idea of your roof orientation and potential shading',
        'Remember that solar panels produce most electricity around solar noon (12:00-14:00) — plan your heavy energy use accordingly',
        'Even on cloudy days, panels produce 10-25% of their rated output, so solar works in most climates',
      ],
      he: [
        'התחילו בבדיקת חשבון החשמל שלכם כדי להבין את הצריכה החודשית בקוט"ש — זהו הבסיס לכל תכנון מערכת סולארית',
        'השתמשו בכלים חינמיים כמו Google Earth או SunCalc כדי לקבל מושג גס על כיוון הגג והצללה אפשרית',
        'זכרו שפאנלים מייצרים את רוב החשמל סביב צהריים סולאריים (12:00-14:00) — תכננו את השימוש הכבד באנרגיה בהתאם',
        'גם בימים מעוננים, פאנלים מייצרים 10-25% מהתפוקה הנקובה, כך שסולארי עובד ברוב האקלימים',
      ],
    },
    argentinaContext: {
      en: 'Argentina has excellent solar resources, especially in the northwest provinces (San Juan, Mendoza, Catamarca) where irradiance exceeds 2,000 kWh/m²/year. Even Buenos Aires receives around 1,600 kWh/m²/year, comparable to southern Spain. The country\'s latitude range (22°S to 55°S) means panel tilt angles should be adjusted by region for optimal yield.',
      he: 'לארגנטינה משאבי שמש מצוינים, במיוחד בפרובינציות הצפון-מערביות (סן חואן, מנדוסה, קטמרקה) שם ההקרנה עולה על 2,000 קוט"ש/מ"ר/שנה. גם בבואנוס איירס ההקרנה מגיעה לכ-1,600 קוט"ש/מ"ר/שנה, בדומה לדרום ספרד. טווח קווי הרוחב של המדינה (22°S עד 55°S) מחייב התאמת זווית הפאנלים לפי אזור לתפוקה מיטבית.',
    },
  },
  {
    id: 'solar-panels-101',
    title: { en: 'Solar Panels 101', he: 'פאנלים סולאריים 101' },
    category: 'fundamentals',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    icon: 'LayoutGrid',
    summary: {
      en: 'Learn the differences between monocrystalline, polycrystalline, and thin-film panels.',
      he: 'למדו את ההבדלים בין פאנלים מונוקריסטליים, פוליקריסטליים ודק-שכבתיים.',
    },
    content: {
      en: [
        'Solar panels come in three main types. Monocrystalline panels are made from a single silicon crystal, giving them the highest efficiency (20-24%) and a distinctive black appearance. They perform better in low-light conditions and have the longest lifespan, but cost more per watt. Polycrystalline panels use multiple silicon crystals fused together, resulting in a blue speckled look, slightly lower efficiency (16-20%), and a lower price point.',
        'Thin-film panels are made by depositing photovoltaic material onto a substrate like glass or metal. They are lightweight and flexible, making them ideal for unconventional surfaces, but have lower efficiency (10-13%) and require more roof space. For residential and commercial rooftops in Argentina, monocrystalline panels dominate the market due to their superior performance per square meter.',
        'Key specifications to compare include: wattage (400-600W for modern panels), efficiency percentage, temperature coefficient (how much output drops per degree above 25°C — typically -0.3% to -0.4%/°C), and warranty terms. Most quality panels offer a 25-year performance warranty guaranteeing at least 80% of original output. The temperature coefficient matters especially in hot regions like northern Argentina where rooftop temperatures can exceed 60°C.',
      ],
      he: [
        'פאנלים סולאריים מגיעים בשלושה סוגים עיקריים. פאנלים מונוקריסטליים עשויים מגביש סיליקון יחיד, מה שמעניק להם את הנצילות הגבוהה ביותר (20-24%) ומראה שחור ייחודי. הם מתפקדים טוב יותר בתנאי תאורה נמוכה ובעלי אורך חיים ארוך ביותר, אך עולים יותר לוואט. פאנלים פוליקריסטליים משתמשים במספר גבישי סיליקון ממוזגים יחד, וכתוצאה מכך מראה כחול מנוקד, נצילות מעט נמוכה יותר (16-20%) ומחיר נמוך יותר.',
        'פאנלים דקי-שכבה מיוצרים על ידי הפקדת חומר פוטו-וולטאי על גבי מצע כמו זכוכית או מתכת. הם קלים וגמישים, מה שהופך אותם לאידיאליים למשטחים לא שגרתיים, אך בעלי נצילות נמוכה יותר (10-13%) ודורשים שטח גג גדול יותר. לגגות מגורים ומסחריים בארגנטינה, פאנלים מונוקריסטליים שולטים בשוק בזכות הביצועים המעולים למטר מרובע.',
        'מפרטים מרכזיים להשוואה כוללים: הספק (400-600W לפאנלים מודרניים), אחוז נצילות, מקדם טמפרטורה (כמה התפוקה יורדת לכל מעלה מעל 25°C — בדרך כלל 0.3%- עד 0.4%-/°C), ותנאי אחריות. רוב הפאנלים האיכותיים מציעים אחריות ביצועים ל-25 שנה המבטיחה לפחות 80% מהתפוקה המקורית. מקדם הטמפרטורה חשוב במיוחד באזורים חמים כמו צפון ארגנטינה שם טמפרטורות הגג יכולות לעלות על 60°C.',
      ],
    },
    keyPoints: {
      en: [
        'Monocrystalline panels offer the highest efficiency (20-24%) and best low-light performance but cost more',
        'Polycrystalline panels provide good value with 16-20% efficiency at a lower price per watt',
        'Thin-film panels are lightweight and flexible but need more space due to 10-13% efficiency',
        'Temperature coefficient indicates output loss per degree above 25°C — critical in hot climates',
        'Quality panels carry 25-year performance warranties guaranteeing at least 80% output retention',
      ],
      he: [
        'פאנלים מונוקריסטליים מציעים את הנצילות הגבוהה ביותר (20-24%) וביצועים מיטביים באור נמוך אך יקרים יותר',
        'פאנלים פוליקריסטליים מספקים ערך טוב עם 16-20% נצילות במחיר נמוך יותר לוואט',
        'פאנלים דקי-שכבה קלים וגמישים אך דורשים יותר שטח בגלל 10-13% נצילות',
        'מקדם הטמפרטורה מציין ירידת תפוקה לכל מעלה מעל 25°C — קריטי באקלים חם',
        'פאנלים איכותיים נושאים אחריות ביצועים ל-25 שנה המבטיחה לפחות 80% שימור תפוקה',
      ],
    },
    practicalTips: {
      en: [
        'For limited roof space, choose monocrystalline panels — you will generate more power per square meter',
        'Always check the temperature coefficient — in hot regions like Mendoza, a panel with -0.30%/°C will outperform one with -0.40%/°C by roughly 5% annually',
        'Look for panels with at least a 12-year product warranty and 25-year performance warranty from Tier-1 manufacturers',
        'Bifacial panels can capture reflected light from the back side, boosting output by 5-15% on white or reflective rooftops',
      ],
      he: [
        'לשטח גג מוגבל, בחרו פאנלים מונוקריסטליים — תייצרו יותר חשמל למטר מרובע',
        'בדקו תמיד את מקדם הטמפרטורה — באזורים חמים כמו מנדוסה, פאנל עם 0.30%-/°C יעלה על פאנל עם 0.40%-/°C בכ-5% בשנה',
        'חפשו פאנלים עם אחריות מוצר של 12 שנה לפחות ואחריות ביצועים של 25 שנה מיצרני Tier-1',
        'פאנלים דו-צדדיים (bifacial) יכולים ללכוד אור מוחזר מהצד האחורי ולהגדיל תפוקה ב-5-15% על גגות לבנים או מחזירי אור',
      ],
    },
    argentinaContext: {
      en: 'The Argentine market is dominated by imported monocrystalline panels from Chinese Tier-1 manufacturers (LONGi, JA Solar, Trina Solar, Canadian Solar). EPSE, the state-owned factory in San Juan, produces polycrystalline panels locally at competitive prices with 10-15% cost savings due to no import duties. Import tariffs on solar panels range from 0-5% under the renewable energy incentive program.',
      he: 'השוק הארגנטינאי נשלט על ידי פאנלים מונוקריסטליים מיובאים מיצרני Tier-1 סיניים (LONGi, JA Solar, Trina Solar, Canadian Solar). EPSE, המפעל הממשלתי בסן חואן, מייצר פאנלים פוליקריסטליים מקומיים במחירים תחרותיים עם חיסכון של 10-15% הודות לפטור ממכס. מכסי יבוא על פאנלים סולאריים נעים בין 0-5% במסגרת תוכנית תמריצי אנרגיה מתחדשת.',
    },
  },
  {
    id: 'inverters-101',
    title: { en: 'Inverters Explained', he: 'אינוורטרים — המדריך המלא' },
    category: 'fundamentals',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    icon: 'Cpu',
    summary: {
      en: 'Understand string inverters, microinverters, and hybrid systems with MPPT tracking.',
      he: 'הבינו אינוורטרים מרכזיים, מיקרו-אינוורטרים ומערכות היברידיות עם מעקב MPPT.',
    },
    content: {
      en: [
        'The inverter is the brain of your solar system. It converts the DC electricity from solar panels into AC electricity used by your home and the grid. There are three main types: string inverters, microinverters, and hybrid inverters. String inverters connect multiple panels in a series "string" and convert power centrally. They are the most cost-effective option but have a key weakness — if one panel is shaded, the entire string\'s output drops.',
        'Microinverters are small units attached to each individual panel. They convert DC to AC right at the panel level, meaning shading on one panel does not affect others. They also enable panel-level monitoring and are easier to expand over time. However, they cost 20-30% more than string inverters and have more potential failure points since there are many units on the roof.',
        'Hybrid inverters combine solar inverter functionality with a battery charger, allowing you to store excess solar energy in batteries for use at night or during outages. Most hybrid inverters include Maximum Power Point Tracking (MPPT), an algorithm that continuously adjusts the electrical load to extract the maximum possible power from the panels as conditions change throughout the day.',
      ],
      he: [
        'האינוורטר הוא המוח של המערכת הסולארית. הוא ממיר את חשמל הזרם הישר (DC) מהפאנלים לזרם חילופין (AC) המשמש את הבית והרשת. ישנם שלושה סוגים עיקריים: אינוורטרים מרכזיים (string), מיקרו-אינוורטרים, ואינוורטרים היברידיים. אינוורטרים מרכזיים מחברים מספר פאנלים בסדרה ("שרשרת") וממירים את האנרגיה באופן מרכזי. זוהי האופציה החסכונית ביותר, אך יש לה חולשה מרכזית — אם פאנל אחד מוצל, התפוקה של כל השרשרת יורדת.',
        'מיקרו-אינוורטרים הם יחידות קטנות המחוברות לכל פאנל בנפרד. הם ממירים DC ל-AC ישירות ברמת הפאנל, כך שהצללה על פאנל אחד לא משפיעה על האחרים. הם גם מאפשרים ניטור ברמת הפאנל וקלים להרחבה לאורך זמן. עם זאת, הם עולים 20-30% יותר מאינוורטרים מרכזיים ויש להם יותר נקודות כשל פוטנציאליות מכיוון שיש יחידות רבות על הגג.',
        'אינוורטרים היברידיים משלבים פונקציונליות של אינוורטר סולארי עם מטען סוללות, ומאפשרים לאחסן עודפי אנרגיה סולארית בסוללות לשימוש בלילה או בזמן הפסקות חשמל. רוב האינוורטרים ההיברידיים כוללים מעקב נקודת הספק מרבית (MPPT), אלגוריתם שמכוונן באופן רציף את העומס החשמלי כדי לחלץ את ההספק המרבי האפשרי מהפאנלים ככל שהתנאים משתנים לאורך היום.',
      ],
    },
    keyPoints: {
      en: [
        'String inverters are cheapest but suffer from the "Christmas light effect" — one shaded panel reduces the entire string output',
        'Microinverters optimize each panel independently, ideal for roofs with partial shading or multiple orientations',
        'Hybrid inverters add battery storage capability for energy independence and backup power',
        'MPPT (Maximum Power Point Tracking) algorithms maximize energy harvest by continuously adjusting electrical load',
        'Inverter efficiency typically ranges from 96-99%, meaning only 1-4% of energy is lost in conversion',
      ],
      he: [
        'אינוורטרים מרכזיים זולים ביותר אך סובלים מ"אפקט שרשרת האורות" — פאנל מוצל אחד מפחית את תפוקת כל השרשרת',
        'מיקרו-אינוורטרים מייעלים כל פאנל באופן עצמאי, אידיאלי לגגות עם הצללה חלקית או כיוונים מרובים',
        'אינוורטרים היברידיים מוסיפים יכולת אחסון בסוללות לעצמאות אנרגטית וגיבוי חשמל',
        'אלגוריתמי MPPT ממקסמים את קציר האנרגיה על ידי כוונון רציף של העומס החשמלי',
        'נצילות אינוורטר נעה בדרך כלל בין 96-99%, כלומר רק 1-4% מהאנרגיה אובדת בהמרה',
      ],
    },
    practicalTips: {
      en: [
        'For simple roofs with no shading, a string inverter offers the best value — brands like Growatt and GoodWe are popular in Argentina',
        'If your roof has chimneys, antennas, or trees causing partial shade, invest in microinverters or power optimizers',
        'Size your inverter at 80-100% of your total panel wattage — slight undersizing (e.g., 5 kW inverter for 6 kWp panels) is common and cost-effective',
        'Choose an inverter with built-in Wi-Fi monitoring so you can track production from your phone',
      ],
      he: [
        'לגגות פשוטים ללא הצללה, אינוורטר מרכזי מציע את הערך הטוב ביותר — מותגים כמו Growatt ו-GoodWe פופולריים בארגנטינה',
        'אם בגג שלכם יש ארובות, אנטנות או עצים שגורמים להצללה חלקית, השקיעו במיקרו-אינוורטרים או מייעלי הספק',
        'תכננו את גודל האינוורטר ב-80-100% מסך ההספק הכולל של הפאנלים — הקטנה קלה (למשל, אינוורטר 5 kW ל-6 kWp פאנלים) נפוצה וחסכונית',
        'בחרו אינוורטר עם ניטור Wi-Fi מובנה כדי שתוכלו לעקוב אחר הייצור מהטלפון',
      ],
    },
    argentinaContext: {
      en: 'Growatt, Solis, and GoodWe are the most popular inverter brands in Argentina due to competitive pricing and local distributor support. Fronius and Huawei are premium options for commercial installations. The Argentine grid frequency is 50 Hz — ensure any imported inverter supports this standard. Hybrid inverters are growing in popularity due to occasional grid instability in some provinces.',
      he: 'Growatt, Solis ו-GoodWe הם מותגי האינוורטרים הפופולריים ביותר בארגנטינה בזכות תמחור תחרותי ותמיכת מפיצים מקומיים. Fronius ו-Huawei הם אופציות פרימיום להתקנות מסחריות. תדר הרשת הארגנטינאי הוא 50 Hz — ודאו שכל אינוורטר מיובא תומך בתקן זה. אינוורטרים היברידיים צוברים פופולריות בגלל חוסר יציבות רשת מזדמן בחלק מהפרובינציות.',
    },
  },
  {
    id: 'net-metering',
    title: { en: 'Net Metering & Net Billing', he: 'מדידה נטו וחיוב נטו' },
    category: 'fundamentals',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    icon: 'ArrowLeftRight',
    summary: {
      en: 'Learn how excess solar energy is credited and the difference between net metering and net billing.',
      he: 'למדו כיצד מזוכים על עודפי אנרגיה סולארית וההבדל בין מדידה נטו לחיוב נטו.',
    },
    content: {
      en: [
        'When your solar system produces more electricity than you consume, the excess flows back into the grid. How you get compensated for this surplus depends on the policy in place. Net metering gives you a one-for-one credit: every kWh you export offsets a kWh you import later, effectively spinning your meter backward. This is the most favorable arrangement for solar owners because you get full retail value for your exported energy.',
        'Net billing (also called feed-in tariff or net billing) compensates you at a different rate for exported energy — usually the wholesale electricity price, which is significantly lower than the retail rate you pay. For example, if you pay $0.15/kWh for electricity but only receive $0.05/kWh for exports, the economics favor maximizing self-consumption rather than exporting to the grid.',
        'Understanding which system applies in your area is critical for financial planning. Under net billing, strategies like shifting heavy loads (washing machines, water heaters, EV charging) to daytime hours when solar is producing become much more important. Battery storage also becomes more financially attractive under net billing since storing energy for evening use saves you the full retail rate instead of earning the lower export rate.',
      ],
      he: [
        'כאשר המערכת הסולארית שלכם מייצרת יותר חשמל ממה שאתם צורכים, העודף זורם בחזרה לרשת. האופן שבו מפצים אתכם על עודף זה תלוי במדיניות הנהוגה. מדידה נטו נותנת לכם זיכוי אחד לאחד: כל קוט"ש שאתם מייצאים מקזז קוט"ש שאתם מייבאים מאוחר יותר, ולמעשה מסובב את המונה לאחור. זהו ההסדר הנוח ביותר לבעלי מערכות סולאריות כי מקבלים ערך קמעונאי מלא עבור האנרגיה המיוצאת.',
        'חיוב נטו (נקרא גם תעריף הזנה או net billing) מפצה אתכם בתעריף שונה עבור אנרגיה מיוצאת — בדרך כלל מחיר חשמל סיטונאי, שנמוך משמעותית מהתעריף הקמעונאי שאתם משלמים. לדוגמה, אם אתם משלמים $0.15/קוט"ש עבור חשמל אך מקבלים רק $0.05/קוט"ש על יצוא, הכלכלה מעדיפה מקסום צריכה עצמית על פני יצוא לרשת.',
        'הבנת איזו מערכת חלה באזור שלכם קריטית לתכנון פיננסי. תחת חיוב נטו, אסטרטגיות כמו הסטת עומסים כבדים (מכונות כביסה, דודי מים, טעינת רכב חשמלי) לשעות היום כשהסולארי מייצר הופכות חשובות הרבה יותר. גם אחסון בסוללות הופך לאטרקטיבי יותר פיננסית תחת חיוב נטו, שכן אחסון אנרגיה לשימוש ערבי חוסך לכם את התעריף הקמעונאי המלא במקום להרוויח את תעריף היצוא הנמוך.',
      ],
    },
    keyPoints: {
      en: [
        'Net metering provides one-for-one credit — exported kWh offsets imported kWh at full retail value',
        'Net billing compensates exports at wholesale rates, which are typically 50-70% lower than retail',
        'Argentina uses net billing under Ley 27.424, meaning self-consumption is more valuable than export',
        'Maximizing self-consumption (using solar energy when it is produced) improves ROI under net billing',
        'Battery storage becomes more financially attractive when export rates are much lower than import rates',
      ],
      he: [
        'מדידה נטו מספקת זיכוי אחד לאחד — קוט"ש מיוצא מקזז קוט"ש מיובא בערך קמעונאי מלא',
        'חיוב נטו מפצה על יצוא בתעריפים סיטונאיים, שנמוכים בדרך כלל ב-50-70% מהקמעונאיים',
        'ארגנטינה משתמשת בחיוב נטו תחת חוק 27.424, כלומר צריכה עצמית יקרה יותר מיצוא',
        'מקסום צריכה עצמית (שימוש באנרגיה סולארית כשהיא מיוצרת) משפר החזר השקעה תחת חיוב נטו',
        'אחסון בסוללות הופך לאטרקטיבי יותר פיננסית כאשר תעריפי יצוא נמוכים הרבה מתעריפי יבוא',
      ],
    },
    practicalTips: {
      en: [
        'Check your local utility\'s interconnection policy before designing your system — credits may expire monthly or carry over annually',
        'Under net billing, schedule dishwashers, laundry, and pool pumps during peak solar hours (10:00-15:00) to maximize self-consumption',
        'Consider installing a smart energy management system that automatically diverts excess production to water heaters or EV chargers',
        'Size your system to cover 80-90% of annual consumption rather than 100% — oversizing leads to exported energy compensated at lower rates',
      ],
      he: [
        'בדקו את מדיניות החיבור של חברת החשמל המקומית לפני תכנון המערכת — זיכויים עשויים לפוג חודשית או להצטבר שנתית',
        'תחת חיוב נטו, תזמנו מדיחי כלים, כביסה ומשאבות בריכה בשעות שיא סולאריות (10:00-15:00) למקסום צריכה עצמית',
        'שקלו התקנת מערכת ניהול אנרגיה חכמה שמפנה אוטומטית עודפי ייצור לדודי מים או מטעני רכב חשמלי',
        'תכננו את המערכת לכסות 80-90% מהצריכה השנתית ולא 100% — מערכת גדולה מדי מובילה לאנרגיה מיוצאת המפוצה בתעריפים נמוכים',
      ],
    },
    argentinaContext: {
      en: 'Argentina\'s Ley 27.424 establishes a net billing framework where prosumers receive credit at the wholesale energy price (costo de la energía) rather than the full retail tariff. Each province implements this differently — Buenos Aires (EDENOR/EDESUR), Mendoza (EMESA), and San Juan have active programs. Credits typically carry over for up to 12 months. The 350% tariff increase in 2024 has dramatically improved the economics of self-consumption.',
      he: 'חוק 27.424 של ארגנטינה מקים מסגרת חיוב נטו שבה פרוסיומרים מקבלים זיכוי במחיר האנרגיה הסיטונאי (costo de la energía) ולא בתעריף הקמעונאי המלא. כל פרובינציה מיישמת זאת אחרת — בואנוס איירס (EDENOR/EDESUR), מנדוסה (EMESA) וסן חואן בעלי תוכניות פעילות. זיכויים בדרך כלל נצברים עד 12 חודשים. עליית התעריפים של 350% ב-2024 שיפרה דרמטית את הכלכלה של צריכה עצמית.',
    },
  },
  {
    id: 'grid-tied-systems',
    title: { en: 'Grid-Tied vs Off-Grid Systems', he: 'מערכות מחוברות רשת מול עצמאיות' },
    category: 'fundamentals',
    difficulty: 'beginner',
    estimatedMinutes: 10,
    icon: 'Network',
    summary: {
      en: 'Compare on-grid, off-grid, and hybrid solar system architectures.',
      he: 'השוו בין ארכיטקטורות מערכת סולארית מחוברת לרשת, עצמאית והיברידית.',
    },
    content: {
      en: [
        'Grid-tied (on-grid) systems are connected to the utility grid and are the most common and cost-effective type of solar installation. They consist of solar panels, an inverter, and a bidirectional meter. When your panels produce more than you need, excess power flows to the grid. When you need more than your panels produce (at night or on cloudy days), you draw from the grid as usual. Grid-tied systems have no batteries, which significantly reduces cost and complexity.',
        'Off-grid systems operate completely independently from the utility grid. They require battery storage to provide power when solar production is insufficient — at night or during extended cloudy periods. Off-grid systems are more expensive due to battery costs and typically require a backup generator for extended periods of low sunlight. They are mainly used in remote areas where connecting to the grid is prohibitively expensive or impossible.',
        'Hybrid systems combine the best of both worlds: they are connected to the grid but also include battery storage. During the day, excess solar charges the batteries first, and any remaining surplus is exported to the grid. At night or during outages, the batteries provide power. This configuration offers energy security while still benefiting from grid connection. The cost falls between grid-tied and off-grid systems.',
      ],
      he: [
        'מערכות מחוברות רשת (on-grid) מחוברות לרשת החשמל והן הסוג הנפוץ והחסכוני ביותר של התקנה סולארית. הן מורכבות מפאנלים סולאריים, אינוורטר ומונה דו-כיווני. כשהפאנלים מייצרים יותר ממה שאתם צריכים, עודף ההספק זורם לרשת. כשאתם צריכים יותר ממה שהפאנלים מייצרים (בלילה או בימים מעוננים), אתם שואבים מהרשת כרגיל. למערכות מחוברות רשת אין סוללות, מה שמפחית משמעותית עלות ומורכבות.',
        'מערכות עצמאיות (off-grid) פועלות באופן עצמאי לחלוטין מרשת החשמל. הן דורשות אחסון בסוללות כדי לספק חשמל כשהייצור הסולארי אינו מספיק — בלילה או בתקופות מעוננות ממושכות. מערכות עצמאיות יקרות יותר בגלל עלויות סוללות ובדרך כלל דורשות גנרטור גיבוי לתקופות ממושכות של מעט שמש. הן משמשות בעיקר באזורים מרוחקים שבהם חיבור לרשת יקר או בלתי אפשרי.',
        'מערכות היברידיות משלבות את הטוב משני העולמות: הן מחוברות לרשת אך כוללות גם אחסון בסוללות. במהלך היום, עודף סולארי טוען קודם את הסוללות, וכל עודף שנותר מיוצא לרשת. בלילה או בזמן הפסקות חשמל, הסוללות מספקות חשמל. תצורה זו מציעה ביטחון אנרגטי תוך שהיא עדיין נהנית מחיבור לרשת. העלות נמצאת בין מערכות מחוברות רשת למערכות עצמאיות.',
      ],
    },
    keyPoints: {
      en: [
        'Grid-tied systems are simplest and cheapest — panels plus inverter, no batteries needed',
        'Off-grid systems require batteries and often a backup generator, adding 40-60% to system cost',
        'Hybrid systems provide backup power during outages while still connected to the grid',
        'Grid-tied systems must shut down during grid outages for safety (anti-islanding protection)',
        'Choose your system type based on grid reliability, budget, and energy independence goals',
      ],
      he: [
        'מערכות מחוברות רשת הן הפשוטות והזולות ביותר — פאנלים ואינוורטר, ללא צורך בסוללות',
        'מערכות עצמאיות דורשות סוללות ולעיתים גנרטור גיבוי, מה שמוסיף 40-60% לעלות המערכת',
        'מערכות היברידיות מספקות חשמל גיבוי בזמן הפסקות תוך חיבור לרשת',
        'מערכות מחוברות רשת חייבות להיכבות בזמן הפסקות חשמל לבטיחות (הגנת אנטי-איילנדינג)',
        'בחרו את סוג המערכת בהתבסס על אמינות הרשת, תקציב ומטרות עצמאות אנרגטית',
      ],
    },
    practicalTips: {
      en: [
        'If your grid is reliable (99%+ uptime), a grid-tied system offers the best return on investment',
        'For areas with frequent outages, a hybrid system with 5-10 kWh battery provides essential backup without the full cost of off-grid',
        'Off-grid systems should be sized for the worst month of solar production, not the best — this prevents winter energy shortfalls',
        'Anti-islanding is a safety requirement — never attempt to bypass it, as it protects utility workers during outages',
      ],
      he: [
        'אם הרשת שלכם אמינה (99%+ זמן פעולה), מערכת מחוברת רשת מציעה את ההחזר הטוב ביותר על ההשקעה',
        'לאזורים עם הפסקות תכופות, מערכת היברידית עם סוללה של 5-10 קוט"ש מספקת גיבוי חיוני ללא העלות המלאה של עצמאית',
        'מערכות עצמאיות צריכות להיות מתוכננות לחודש הגרוע ביותר של ייצור סולארי, לא הטוב ביותר — זה מונע מחסור באנרגיה בחורף',
        'אנטי-איילנדינג הוא דרישת בטיחות — אל תנסו לעקוף אותו, שכן הוא מגן על עובדי חברת החשמל בזמן הפסקות',
      ],
    },
    argentinaContext: {
      en: 'In urban Argentina (Buenos Aires, Rosario, Córdoba), grid-tied systems account for over 90% of residential installations due to reliable grid infrastructure. However, in rural Patagonia and northern provinces, off-grid systems are essential where grid connection costs can exceed $10,000 USD. The national PERMER program (Proyecto de Energías Renovables en Mercados Rurales) provides subsidies for off-grid solar in rural areas.',
      he: 'בארגנטינה העירונית (בואנוס איירס, רוסריו, קורדובה), מערכות מחוברות רשת מהוות מעל 90% מההתקנות הביתיות בזכות תשתית רשת אמינה. עם זאת, בפטגוניה הכפרית ובפרובינציות הצפוניות, מערכות עצמאיות חיוניות כאשר עלויות חיבור לרשת יכולות לעלות על $10,000. תוכנית PERMER הלאומית (Proyecto de Energías Renovables en Mercados Rurales) מספקת סובסידיות לסולארי עצמאי באזורים כפריים.',
    },
  },
  {
    id: 'system-sizing',
    title: { en: 'System Sizing & Design', he: 'תכנון וגודל מערכת' },
    category: 'technology',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    icon: 'Ruler',
    summary: {
      en: 'Learn how to calculate the right system size using peak sun hours, performance ratio, and consumption data.',
      he: 'למדו כיצד לחשב את גודל המערכת הנכון באמצעות שעות שמש שיא, יחס ביצועים ונתוני צריכה.',
    },
    content: {
      en: [
        'System sizing starts with understanding your electricity consumption. Review 12 months of utility bills to find your average monthly consumption in kWh. Seasonal variation matters — you may use more electricity in summer (air conditioning) or winter (heating). The goal is to size a system that covers 80-100% of your annual consumption, accounting for the net billing economics in your region.',
        'The core formula for system sizing is: System Size (kWp) = Annual Consumption (kWh) / (Peak Sun Hours × 365 × Performance Ratio). Peak Sun Hours (PSH) represent the equivalent hours of full sunlight per day at your location — Argentina ranges from 3.8 PSH in Tierra del Fuego to 6.0 PSH in San Juan. The Performance Ratio (PR) accounts for all system losses including inverter efficiency, wiring, soiling, temperature, and shading — typically 75-85% for well-designed systems.',
        'For example, a home in Buenos Aires consuming 400 kWh/month (4,800 kWh/year) with 4.5 PSH and 0.80 PR would need: 4,800 / (4.5 × 365 × 0.80) = 3.65 kWp. With 550W panels, that is 7 panels. Always round up and consider available roof space, shading analysis, and future consumption growth. Commercial systems follow the same formula but must also consider demand charges and time-of-use tariffs.',
      ],
      he: [
        'תכנון גודל המערכת מתחיל בהבנת צריכת החשמל שלכם. סקרו 12 חודשי חשבונות חשמל כדי למצוא את הצריכה הממוצעת החודשית בקוט"ש. שינויים עונתיים חשובים — ייתכן שתשתמשו ביותר חשמל בקיץ (מיזוג) או בחורף (חימום). המטרה היא לתכנן מערכת שמכסה 80-100% מהצריכה השנתית, תוך התחשבות בכלכלת החיוב הנטו באזור שלכם.',
        'הנוסחה המרכזית לתכנון גודל היא: גודל מערכת (kWp) = צריכה שנתית (קוט"ש) / (שעות שמש שיא × 365 × יחס ביצועים). שעות שמש שיא (PSH) מייצגות את השעות המקבילות של שמש מלאה ביום במיקום שלכם — ארגנטינה נעה בין 3.8 PSH בטיירה דל פואגו ל-6.0 PSH בסן חואן. יחס הביצועים (PR) מתחשב בכל הפסדי המערכת כולל נצילות אינוורטר, חיווט, לכלוך, טמפרטורה והצללה — בדרך כלל 75-85% למערכות מתוכננות היטב.',
        'לדוגמה, בית בבואנוס איירס שצורך 400 קוט"ש/חודש (4,800 קוט"ש/שנה) עם 4.5 PSH ו-0.80 PR יזדקק ל: 4,800 / (4.5 × 365 × 0.80) = 3.65 kWp. עם פאנלים של 550W, אלה 7 פאנלים. תמיד עגלו כלפי מעלה ושקלו שטח גג זמין, ניתוח הצללה וצמיחת צריכה עתידית. מערכות מסחריות עוקבות אחרי אותה נוסחה אך חייבות להתחשב גם בעמלות ביקוש ותעריפים לפי שעה.',
      ],
    },
    keyPoints: {
      en: [
        'Always base sizing on 12 months of consumption data to account for seasonal variations',
        'System Size (kWp) = Annual kWh / (Peak Sun Hours × 365 × Performance Ratio)',
        'Performance Ratio (75-85%) accounts for real-world losses: temperature, shading, soiling, wiring, inverter',
        'Peak Sun Hours vary significantly across Argentina — from 3.8 in the south to 6.0 in the northwest',
        'Size for 80-100% of consumption — oversizing leads to exported energy at lower net billing rates',
      ],
      he: [
        'תמיד בססו את הגודל על 12 חודשי נתוני צריכה כדי להתחשב בשינויים עונתיים',
        'גודל מערכת (kWp) = קוט"ש שנתי / (שעות שמש שיא × 365 × יחס ביצועים)',
        'יחס ביצועים (75-85%) מתחשב בהפסדים בפועל: טמפרטורה, הצללה, לכלוך, חיווט, אינוורטר',
        'שעות שמש שיא משתנות משמעותית ברחבי ארגנטינה — מ-3.8 בדרום ל-6.0 בצפון-מערב',
        'תכננו ל-80-100% מהצריכה — מערכת גדולה מדי מובילה ליצוא אנרגיה בתעריפי חיוב נטו נמוכים',
      ],
    },
    practicalTips: {
      en: [
        'Request a detailed consumption history from your utility company — many offer 12-month data downloads through their website',
        'Add 10-15% buffer to your sizing calculation to account for panel degradation over 25 years (0.5% per year)',
        'Use free simulation tools like PVWatts (NREL) or Global Solar Atlas to estimate production at your exact location',
        'For commercial projects, analyze the load profile hour-by-hour to maximize self-consumption and reduce demand charges',
      ],
      he: [
        'בקשו היסטוריית צריכה מפורטת מחברת החשמל — רבות מציעות הורדות נתונים של 12 חודשים דרך האתר שלהן',
        'הוסיפו מרווח של 10-15% לחישוב הגודל כדי להתחשב בדעיכת פאנלים לאורך 25 שנה (0.5% בשנה)',
        'השתמשו בכלי סימולציה חינמיים כמו PVWatts (NREL) או Global Solar Atlas להערכת ייצור במיקום המדויק שלכם',
        'לפרויקטים מסחריים, נתחו את פרופיל העומס שעה-שעה למקסום צריכה עצמית והפחתת עמלות ביקוש',
      ],
    },
    argentinaContext: {
      en: 'Argentine residential tariffs are structured in consumption blocks (R1-R9 for EDENOR/EDESUR) where higher consumption costs progressively more per kWh. This means solar systems that reduce consumption to a lower block can deliver outsized savings. Average residential consumption in Buenos Aires is 300-500 kWh/month, requiring 3-6 kWp systems. Commercial consumers under the T2/T3 tariff categories often benefit from 20-100 kWp systems.',
      he: 'תעריפי מגורים ארגנטינאיים בנויים בבלוקי צריכה (R1-R9 עבור EDENOR/EDESUR) שבהם צריכה גבוהה יותר עולה יותר לקוט"ש. משמעות הדבר שמערכות סולאריות שמפחיתות צריכה לבלוק נמוך יותר יכולות לספק חיסכון גבוה מהצפוי. צריכה ממוצעת למגורים בבואנוס איירס היא 300-500 קוט"ש/חודש, שדורשת מערכות של 3-6 kWp. צרכנים מסחריים תחת קטגוריות תעריף T2/T3 נהנים לעיתים קרובות ממערכות של 20-100 kWp.',
    },
  },
  {
    id: 'balance-of-system',
    title: { en: 'Balance of System (BOS)', he: 'מאזן מערכת (BOS)' },
    category: 'technology',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
    icon: 'Cable',
    summary: {
      en: 'Everything beyond panels and inverters: mounting, cabling, protections, and grounding.',
      he: 'כל מה שמעבר לפאנלים ואינוורטרים: מערכות הרכבה, כבילה, הגנות והארקה.',
    },
    content: {
      en: [
        'Balance of System (BOS) refers to all components of a solar installation beyond the panels and inverter. This typically accounts for 40-50% of total system cost and includes mounting structures, DC and AC cabling, combiner boxes, disconnects, surge protection, grounding, and the electrical meter. Proper BOS design is critical — even the best panels will underperform if mounted incorrectly or wired with undersized cables.',
        'Mounting systems come in several types: flush-mount (parallel to roof surface, most common for residential), tilt-mount (angled frames for flat roofs), ground-mount (free-standing frames), and carport structures. The mounting system must withstand local wind loads and be compatible with the roof type — whether tile, metal sheet, concrete, or membrane. In Argentina, wind loads vary from 30 km/h in sheltered urban areas to over 120 km/h in Patagonia.',
        'Electrical protection components include DC isolators (to safely disconnect panels), AC circuit breakers, surge protection devices (SPDs) to guard against lightning, and a proper grounding system. All cabling must be UV-resistant and appropriately sized to minimize voltage drop — the standard is less than 2% drop on the DC side and less than 1% on the AC side. A bidirectional meter installed by the utility enables net billing measurement.',
      ],
      he: [
        'מאזן מערכת (BOS) מתייחס לכל רכיבי ההתקנה הסולארית מעבר לפאנלים ולאינוורטר. זה בדרך כלל מהווה 40-50% מעלות המערכת הכוללת וכולל מבני הרכבה, כבילה DC ו-AC, קופסאות מאגדות, מנתקים, הגנת נחשולים, הארקה ומונה חשמל. תכנון BOS נכון הוא קריטי — גם הפאנלים הטובים ביותר יתפקדו בצורה ירודה אם יותקנו בצורה שגויה או יחווטו בכבלים בגודל לא מתאים.',
        'מערכות הרכבה מגיעות בכמה סוגים: הרכבה צמודה (מקבילה לפני הגג, הנפוצה ביותר למגורים), הרכבה בזווית (מסגרות בזווית לגגות שטוחים), הרכבה קרקעית (מסגרות עצמאיות), ומבני חניה. מערכת ההרכבה חייבת לעמוד בעומסי רוח מקומיים ולהיות תואמת לסוג הגג — בין אם רעפים, פח, בטון או ממברנה. בארגנטינה, עומסי רוח נעים מ-30 קמ"ש באזורים עירוניים מוגנים ליותר מ-120 קמ"ש בפטגוניה.',
        'רכיבי הגנה חשמלית כוללים מנתקי DC (לניתוק בטוח של פאנלים), מפסקי AC, התקני הגנת נחשולים (SPDs) להגנה מפני ברקים, ומערכת הארקה נכונה. כל הכבילה חייבת להיות עמידה ב-UV ובגודל מתאים למזעור נפילת מתח — התקן הוא פחות מ-2% נפילה בצד DC ופחות מ-1% בצד AC. מונה דו-כיווני המותקן על ידי חברת החשמל מאפשר מדידת חיוב נטו.',
      ],
    },
    keyPoints: {
      en: [
        'BOS components account for 40-50% of total system cost — do not underestimate this budget line',
        'Mounting must be engineered for local wind loads and matched to the specific roof type',
        'DC cable voltage drop should stay below 2%, and AC cable drop below 1% for optimal efficiency',
        'Surge protection devices (SPDs) are essential in lightning-prone regions to protect inverter and panels',
        'A proper grounding system protects against electrical faults and is required by Argentine electrical codes',
      ],
      he: [
        'רכיבי BOS מהווים 40-50% מעלות המערכת הכוללת — אל תזלזלו בשורת תקציב זו',
        'ההרכבה חייבת להיות מתוכננת לעומסי רוח מקומיים ומותאמת לסוג הגג הספציפי',
        'נפילת מתח בכבל DC צריכה להישאר מתחת ל-2%, ובכבל AC מתחת ל-1% לנצילות מיטבית',
        'התקני הגנת נחשולים (SPDs) חיוניים באזורים עם ברקים להגנה על אינוורטר ופאנלים',
        'מערכת הארקה נכונה מגנה מפני תקלות חשמליות ונדרשת על פי תקני החשמל הארגנטינאיים',
      ],
    },
    practicalTips: {
      en: [
        'Always use stainless steel or aluminum mounting hardware — galvanized steel corrodes faster in coastal or humid environments',
        'Label all DC cables clearly with polarity markers and ensure all connectors are the same brand (mixing MC4 brands can cause failures)',
        'Install DC isolators accessible from ground level so firefighters can safely disconnect the system in an emergency',
        'Request a string diagram from your installer showing exactly how panels are connected — this is essential for future troubleshooting',
      ],
      he: [
        'השתמשו תמיד בחומרת הרכבה מנירוסטה או אלומיניום — פלדה מגולוונת מתקלקלת מהר יותר בסביבות חוף או לחות',
        'סמנו את כל כבלי ה-DC בבירור עם סימני קוטביות וודאו שכל המחברים מאותו מותג (ערבוב מותגי MC4 עלול לגרום לכשלים)',
        'התקינו מנתקי DC נגישים מגובה הקרקע כדי שכבאים יוכלו לנתק את המערכת בבטחה במקרה חירום',
        'בקשו מהמתקין תרשים שרשרות שמראה בדיוק כיצד הפאנלים מחוברים — זה חיוני לפתרון בעיות עתידי',
      ],
    },
    argentinaContext: {
      en: 'Argentine electrical installations must comply with AEA (Asociación Electrotécnica Argentina) standards, specifically AEA 90364 for low-voltage installations. BOS costs in Argentina average $450-700 USD per kWp, which is higher than global averages due to import duties on components like MC4 connectors, cable, and mounting rails. Local manufacturers like Solucion Solar offer domestically produced mounting structures at competitive prices.',
      he: 'התקנות חשמליות בארגנטינה חייבות לעמוד בתקני AEA (Asociación Electrotécnica Argentina), במיוחד AEA 90364 להתקנות מתח נמוך. עלויות BOS בארגנטינה ממוצעות ב-$450-700 דולר לכל kWp, שזה גבוה מהממוצע העולמי בגלל מכסי יבוא על רכיבים כמו מחברי MC4, כבלים ומסילות הרכבה. יצרנים מקומיים כמו Solucion Solar מציעים מבני הרכבה מיוצרים מקומית במחירים תחרותיים.',
    },
  },
  {
    id: 'monitoring-systems',
    title: { en: 'Monitoring & Performance Tracking', he: 'ניטור ומעקב ביצועים' },
    category: 'technology',
    difficulty: 'intermediate',
    estimatedMinutes: 12,
    icon: 'Monitor',
    summary: {
      en: 'Track your solar system performance with monitoring platforms and understand key metrics.',
      he: 'עקבו אחר ביצועי המערכת הסולארית עם פלטפורמות ניטור והבינו מדדים מרכזיים.',
    },
    content: {
      en: [
        'Solar monitoring systems track your installation\'s performance in real-time, allowing you to detect issues quickly and verify that your system is producing as expected. Most modern inverters include built-in monitoring via Wi-Fi or cellular connection, with data accessible through mobile apps and web portals. Popular platforms include SolarEdge Monitoring, Huawei FusionSolar, Growatt ShineServer, and Solis Cloud.',
        'The key metrics to track are: daily/monthly/annual energy production (kWh), specific yield (kWh per kWp installed), performance ratio (actual vs theoretical production), and capacity factor. A well-performing system in Buenos Aires should produce 1,400-1,600 kWh per kWp per year. If your specific yield drops below expected values, it could indicate soiling, shading, inverter faults, or panel degradation.',
        'Advanced monitoring at the panel level (available with microinverters or power optimizers) lets you identify underperforming individual panels. Set up automated alerts for production drops exceeding 15-20% from expected values, inverter errors, or communication failures. Regular monitoring data review — at least monthly — helps catch small issues before they become expensive problems.',
      ],
      he: [
        'מערכות ניטור סולאריות עוקבות אחר ביצועי ההתקנה בזמן אמת, ומאפשרות לזהות בעיות במהירות ולוודא שהמערכת מייצרת כצפוי. רוב האינוורטרים המודרניים כוללים ניטור מובנה דרך Wi-Fi או חיבור סלולרי, עם נתונים נגישים דרך אפליקציות ניידות ופורטלים באינטרנט. פלטפורמות פופולריות כוללות SolarEdge Monitoring, Huawei FusionSolar, Growatt ShineServer ו-Solis Cloud.',
        'המדדים המרכזיים למעקב הם: ייצור אנרגיה יומי/חודשי/שנתי (קוט"ש), תפוקה ספציפית (קוט"ש לכל kWp מותקן), יחס ביצועים (ייצור בפועל מול תיאורטי), ומקדם ניצולת. מערכת מתפקדת היטב בבואנוס איירס צריכה לייצר 1,400-1,600 קוט"ש לכל kWp בשנה. אם התפוקה הספציפית יורדת מתחת לערכים הצפויים, זה עשוי להצביע על לכלוך, הצללה, תקלות אינוורטר או דעיכת פאנלים.',
        'ניטור מתקדם ברמת הפאנל (זמין עם מיקרו-אינוורטרים או מייעלי הספק) מאפשר לזהות פאנלים בודדים בעלי ביצועים נמוכים. הגדירו התראות אוטומטיות לירידות ייצור העולות על 15-20% מהערכים הצפויים, שגיאות אינוורטר או כשלי תקשורת. סקירה קבועה של נתוני ניטור — לפחות חודשית — עוזרת לתפוס בעיות קטנות לפני שהן הופכות לבעיות יקרות.',
      ],
    },
    keyPoints: {
      en: [
        'Most modern inverters include free monitoring apps — SolarEdge, Huawei FusionSolar, Growatt ShineServer, Solis Cloud',
        'Specific yield (kWh/kWp/year) is the best metric for comparing system performance across different system sizes',
        'A healthy system in Buenos Aires should produce 1,400-1,600 kWh per kWp per year',
        'Panel-level monitoring (via microinverters or optimizers) pinpoints individual underperforming modules',
        'Set automated alerts for production drops exceeding 15-20% to catch issues early',
      ],
      he: [
        'רוב האינוורטרים המודרניים כוללים אפליקציות ניטור חינמיות — SolarEdge, Huawei FusionSolar, Growatt ShineServer, Solis Cloud',
        'תפוקה ספציפית (קוט"ש/kWp/שנה) היא המדד הטוב ביותר להשוואת ביצועי מערכות בגדלים שונים',
        'מערכת בריאה בבואנוס איירס צריכה לייצר 1,400-1,600 קוט"ש לכל kWp בשנה',
        'ניטור ברמת פאנל (דרך מיקרו-אינוורטרים או מייעלים) מאתר מודולים בודדים בעלי ביצועים נמוכים',
        'הגדירו התראות אוטומטיות לירידות ייצור העולות על 15-20% לזיהוי מוקדם של בעיות',
      ],
    },
    practicalTips: {
      en: [
        'Compare your actual monthly production against the simulation estimate from your installer — deviations above 10% warrant investigation',
        'Check monitoring data after rainy seasons and dusty periods — a sudden production increase after rain confirms soiling was an issue',
        'Export your production data quarterly to a spreadsheet for long-term trend analysis and degradation tracking',
        'If your inverter lacks built-in monitoring, third-party devices like Solar Analytics or Sense can be added for around $200-400 USD',
      ],
      he: [
        'השוו את הייצור החודשי בפועל מול הערכת הסימולציה מהמתקין — סטיות מעל 10% מצדיקות חקירה',
        'בדקו נתוני ניטור אחרי עונות גשמים ותקופות מאובקות — עלייה פתאומית בייצור אחרי גשם מאשרת שלכלוך היה בעיה',
        'ייצאו את נתוני הייצור רבעונית לגיליון אלקטרוני לניתוח מגמות ארוך טווח ומעקב אחר דעיכה',
        'אם לאינוורטר אין ניטור מובנה, ניתן להוסיף מכשירים של צד שלישי כמו Solar Analytics או Sense בכ-$200-400',
      ],
    },
    argentinaContext: {
      en: 'In Argentina, Growatt ShineServer and Solis Cloud are the most commonly used monitoring platforms due to the market dominance of these inverter brands. SolarEdge and Huawei FusionSolar are used in premium commercial installations. Internet connectivity can be unreliable in rural provinces, so cellular-based monitoring (4G dongle) is often preferred over Wi-Fi for remote installations. Some Argentine installers offer monitoring-as-a-service packages for ongoing O&M.',
      he: 'בארגנטינה, Growatt ShineServer ו-Solis Cloud הם פלטפורמות הניטור הנפוצות ביותר בגלל הדומיננטיות של מותגי אינוורטרים אלה בשוק. SolarEdge ו-Huawei FusionSolar משמשים בהתקנות מסחריות פרימיום. קישוריות אינטרנט עשויה להיות לא אמינה בפרובינציות כפריות, ולכן ניטור מבוסס סלולרי (דונגל 4G) מועדף לעיתים קרובות על פני Wi-Fi להתקנות מרוחקות. חלק מהמתקינים הארגנטינאיים מציעים חבילות ניטור כשירות לתחזוקה שוטפת.',
    },
  },
  {
    id: 'financial-metrics',
    title: { en: 'Financial Metrics for Solar', he: 'מדדים פיננסיים לסולארי' },
    category: 'economics',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    icon: 'TrendingUp',
    summary: {
      en: 'Master ROI, IRR, NPV, LCOE, and payback period calculations for solar investments.',
      he: 'שלטו בחישובי ROI, IRR, NPV, LCOE ותקופת החזר להשקעות סולאריות.',
    },
    content: {
      en: [
        'Evaluating a solar investment requires understanding five key financial metrics. Return on Investment (ROI) measures total profit as a percentage of initial cost over the system lifetime. For a $10,000 system that saves $40,000 over 25 years, ROI = ($40,000 - $10,000) / $10,000 = 300%. Simple Payback Period is how long it takes for cumulative savings to equal the initial investment — typically 3-7 years in Argentina depending on tariff category and location.',
        'Net Present Value (NPV) accounts for the time value of money by discounting future savings to today\'s value. A positive NPV means the investment creates value beyond the discount rate. Internal Rate of Return (IRR) is the discount rate at which NPV equals zero — think of it as the "interest rate" your solar investment earns. A residential solar system in Argentina might have an IRR of 15-35%, far exceeding bank deposit rates or bond yields.',
        'Levelized Cost of Energy (LCOE) divides total lifetime system cost (including maintenance and panel degradation) by total lifetime energy production to give a cost per kWh. If your LCOE is lower than your electricity tariff, solar is financially beneficial. In Argentina, solar LCOE is approximately $0.04-0.07/kWh, while residential tariffs after the 2024 increases range from $0.08-0.15/kWh, creating a clear economic advantage.',
      ],
      he: [
        'הערכת השקעה סולארית דורשת הבנה של חמישה מדדים פיננסיים מרכזיים. תשואה על השקעה (ROI) מודדת רווח כולל כאחוז מהעלות ההתחלתית על פני חיי המערכת. למערכת של $10,000 שחוסכת $40,000 על פני 25 שנה, ROI = ($40,000 - $10,000) / $10,000 = 300%. תקופת החזר פשוטה היא כמה זמן לוקח לחיסכון המצטבר להשתוות להשקעה ההתחלתית — בדרך כלל 3-7 שנים בארגנטינה בהתאם לקטגוריית תעריף ומיקום.',
        'ערך נוכחי נקי (NPV) מתחשב בערך הזמן של הכסף על ידי היוון חיסכון עתידי לערך של היום. NPV חיובי משמעו שההשקעה יוצרת ערך מעבר לשיעור ההיוון. שיעור תשואה פנימי (IRR) הוא שיעור ההיוון שבו NPV שווה לאפס — חשבו עליו כ"שיעור ריבית" שההשקעה הסולארית שלכם מרוויחה. מערכת סולארית ביתית בארגנטינה עשויה להיות בעלת IRR של 15-35%, הרבה מעבר לשיעורי פיקדון בנקאיים או תשואות אגרות חוב.',
        'עלות אנרגיה ממוצעת (LCOE) מחלקת את עלות המערכת הכוללת לאורך חייה (כולל תחזוקה ודעיכת פאנלים) בייצור האנרגיה הכולל לאורך חייה כדי לתת עלות לקוט"ש. אם ה-LCOE שלכם נמוך מתעריף החשמל, סולארי משתלם כלכלית. בארגנטינה, LCOE סולארי הוא כ-$0.04-0.07/קוט"ש, בעוד תעריפי מגורים אחרי העלאות 2024 נעים בין $0.08-0.15/קוט"ש, מה שיוצר יתרון כלכלי ברור.',
      ],
    },
    keyPoints: {
      en: [
        'ROI measures total percentage return over system lifetime — typically 200-400% for well-designed solar systems',
        'Simple payback period in Argentina is 3-7 years depending on tariff, location, and system cost',
        'NPV above zero means the investment creates value — use 8-12% discount rate for Argentine peso calculations',
        'IRR for residential solar in Argentina ranges 15-35%, outperforming most traditional investments',
        'LCOE ($0.04-0.07/kWh for solar) vs retail tariff ($0.08-0.15/kWh) demonstrates the economic case',
      ],
      he: [
        'ROI מודד תשואה אחוזית כוללת על פני חיי המערכת — בדרך כלל 200-400% למערכות סולאריות מתוכננות היטב',
        'תקופת החזר פשוטה בארגנטינה היא 3-7 שנים בהתאם לתעריף, מיקום ועלות מערכת',
        'NPV מעל אפס משמעו שההשקעה יוצרת ערך — השתמשו בשיעור היוון של 8-12% לחישובי פזו ארגנטינאי',
        'IRR לסולארי ביתי בארגנטינה נע בין 15-35%, עולה על ביצועי רוב ההשקעות המסורתיות',
        'LCOE ($0.04-0.07/קוט"ש לסולארי) מול תעריף קמעונאי ($0.08-0.15/קוט"ש) מדגים את המקרה הכלכלי',
      ],
    },
    practicalTips: {
      en: [
        'Always calculate in USD when comparing solar investments in Argentina — peso inflation distorts long-term projections',
        'Use a conservative 2-3% annual electricity price increase (in USD terms) in your financial model rather than optimistic assumptions',
        'Factor in 0.5% annual panel degradation when calculating lifetime energy production',
        'Compare solar IRR against alternative investments: Argentine bank deposits (3-5% USD), US Treasury bonds (4-5%), or local real estate',
      ],
      he: [
        'חשבו תמיד בדולרים כשמשווים השקעות סולאריות בארגנטינה — אינפלציית הפזו מעוותת תחזיות ארוכות טווח',
        'השתמשו בעליית מחירי חשמל שנתית שמרנית של 2-3% (במונחי דולר) במודל הפיננסי במקום הנחות אופטימיות',
        'הכניסו בחשבון דעיכת פאנלים שנתית של 0.5% בחישוב ייצור אנרגיה לאורך חיי המערכת',
        'השוו IRR סולארי מול השקעות חלופיות: פיקדונות בנקאיים ארגנטינאיים (3-5% דולר), אג"ח ממשלת ארה"ב (4-5%), או נדל"ן מקומי',
      ],
    },
    argentinaContext: {
      en: 'The 350% electricity tariff increase in 2024 dramatically shortened solar payback periods across Argentina. Before the increase, residential payback was 8-12 years; now it is 3-5 years for most cases. Commercial consumers on the T3 tariff (medium voltage) see even faster payback of 2.5-4 years. When modeling finances, use the parallel USD exchange rate (dólar blue or MEP) rather than the official rate for realistic cost calculations. The annual inflation rate exceeding 100% makes peso-denominated analysis meaningless — always model in USD.',
      he: 'עליית תעריפי החשמל של 350% ב-2024 קיצרה דרמטית את תקופות ההחזר הסולאריות ברחבי ארגנטינה. לפני העלייה, החזר למגורים היה 8-12 שנים; כעת הוא 3-5 שנים ברוב המקרים. צרכנים מסחריים בתעריף T3 (מתח בינוני) רואים החזר מהיר אף יותר של 2.5-4 שנים. בעת מידול פיננסי, השתמשו בשער הדולר המקביל (דולר בלו או MEP) ולא בשער הרשמי לחישובי עלות ריאליסטיים. שיעור האינפלציה השנתי העולה על 100% הופך ניתוח בפזו לחסר משמעות — תמיד מדלו בדולרים.',
    },
  },
  {
    id: 'argentina-tariffs',
    title: { en: 'Argentine Electricity Tariffs', he: 'תעריפי חשמל בארגנטינה' },
    category: 'economics',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    icon: 'Zap',
    summary: {
      en: 'Navigate the SEF tariff system, subsidy removal, and the 350% rate increase impact.',
      he: 'נווטו במערכת תעריפי SEF, הסרת סובסידיות והשפעת העלאת המחירים של 350%.',
    },
    content: {
      en: [
        'Argentina\'s electricity tariff system is managed through the SEF (Subsidio a la Energía Federal) framework. For decades, massive government subsidies kept electricity prices artificially low, making solar economically unviable. In 2024, the Milei government removed most subsidies, resulting in tariff increases exceeding 350% for residential consumers and even more for commercial users. This single policy change transformed the solar market overnight.',
        'Residential tariffs are structured in consumption blocks. EDENOR and EDESUR (the two main distributors in Greater Buenos Aires) use categories R1 through R9, where higher consumption pays progressively more per kWh. The first 150 kWh/month is cheapest, with costs escalating sharply above 300 kWh/month. This tiered structure means solar systems that push consumption into a lower tier deliver outsized savings — not just on the kWh replaced but on the rate reduction for remaining consumption.',
        'Commercial and industrial tariffs (T2 for low voltage, T3 for medium voltage) include both energy charges (per kWh) and demand charges (per kW of peak demand). This dual pricing means commercial solar systems provide value two ways: reducing energy consumption and potentially lowering peak demand charges. Time-of-use tariffs in some provinces charge more during peak hours (18:00-23:00), which does not align with solar production but makes battery storage more attractive.',
      ],
      he: [
        'מערכת תעריפי החשמל של ארגנטינה מנוהלת דרך מסגרת SEF (Subsidio a la Energía Federal). במשך עשורים, סובסידיות ממשלתיות ענקיות שמרו על מחירי חשמל נמוכים באופן מלאכותי, מה שהפך סולארי ללא כדאי כלכלית. ב-2024, ממשלת מיליי הסירה את רוב הסובסידיות, מה שגרם לעליות תעריף העולות על 350% לצרכנים ביתיים ואף יותר לצרכנים מסחריים. שינוי מדיניות יחיד זה שינה את שוק הסולארי בן לילה.',
        'תעריפי מגורים בנויים בבלוקי צריכה. EDENOR ו-EDESUR (שני המפיצים העיקריים בבואנוס איירס הגדולה) משתמשים בקטגוריות R1 עד R9, שבהן צריכה גבוהה יותר משלמת יותר לקוט"ש באופן פרוגרסיבי. 150 קוט"ש/חודש הראשונים הם הזולים ביותר, עם עלויות המסלימות בחדות מעל 300 קוט"ש/חודש. מבנה מדורג זה אומר שמערכות סולאריות שדוחפות צריכה למדרגה נמוכה יותר מספקות חיסכון מוגזם — לא רק על הקוט"ש שהוחלף אלא על הפחתת התעריף לצריכה הנותרת.',
        'תעריפים מסחריים ותעשייתיים (T2 למתח נמוך, T3 למתח בינוני) כוללים גם חיובי אנרגיה (לקוט"ש) וגם חיובי ביקוש (לכל kW של ביקוש שיא). תמחור כפול זה אומר שמערכות סולאריות מסחריות מספקות ערך בשני דרכים: הפחתת צריכת אנרגיה ועשויות להוריד חיובי ביקוש שיא. תעריפים לפי שעה בחלק מהפרובינציות גובים יותר בשעות שיא (18:00-23:00), שלא חופף עם ייצור סולארי אך הופך אחסון בסוללות לאטרקטיבי יותר.',
      ],
    },
    keyPoints: {
      en: [
        'The 2024 subsidy removal caused 350%+ tariff increases, making solar financially viable for the first time',
        'Residential tariffs use progressive blocks — reducing consumption to a lower tier amplifies savings',
        'Commercial T2/T3 tariffs include demand charges (per kW) in addition to energy charges (per kWh)',
        'EDENOR and EDESUR serve Greater Buenos Aires; each province has its own distributor and rate structure',
        'Time-of-use tariffs charge more during evening peak (18:00-23:00), not during solar production hours',
      ],
      he: [
        'הסרת הסובסידיות ב-2024 גרמה לעליות תעריף של מעל 350%, מה שהפך סולארי לכדאי פיננסית לראשונה',
        'תעריפי מגורים משתמשים בבלוקים פרוגרסיביים — הפחתת צריכה למדרגה נמוכה יותר מגבירה את החיסכון',
        'תעריפי T2/T3 מסחריים כוללים חיובי ביקוש (לכל kW) בנוסף לחיובי אנרגיה (לקוט"ש)',
        'EDENOR ו-EDESUR משרתות את בואנוס איירס הגדולה; לכל פרובינציה יש מפיץ ומבנה תעריפים משלה',
        'תעריפים לפי שעה גובים יותר בשיא הערב (18:00-23:00), לא בשעות ייצור סולארי',
      ],
    },
    practicalTips: {
      en: [
        'Obtain your full tariff schedule from your distributor\'s website — knowing your exact rate per block is essential for accurate savings calculations',
        'Check if you qualify for the "tarifa social" (social tariff) subsidy — if you do, solar payback will be longer since your baseline cost is lower',
        'For commercial projects, request 12 months of demand data to identify peak demand periods and size your system accordingly',
        'Monitor government announcements for further tariff adjustments — prices are still being gradually deregulated and may continue rising',
      ],
      he: [
        'השיגו את לוח התעריפים המלא מאתר המפיץ — הכרת התעריף המדויק לכל בלוק חיונית לחישובי חיסכון מדויקים',
        'בדקו אם אתם זכאים לסובסידיית "tarifa social" (תעריף חברתי) — אם כן, ההחזר הסולארי יהיה ארוך יותר מכיוון שעלות הבסיס נמוכה יותר',
        'לפרויקטים מסחריים, בקשו 12 חודשי נתוני ביקוש לזיהוי תקופות ביקוש שיא ותכנון המערכת בהתאם',
        'עקבו אחר הכרזות ממשלה לגבי התאמות תעריף נוספות — המחירים עדיין עוברים הסרת פיקוח הדרגתית ועשויים להמשיך לעלות',
      ],
    },
    argentinaContext: {
      en: 'As of February 2026, residential electricity costs in Buenos Aires average ARS 80-150 per kWh depending on consumption block (approximately $0.06-0.10 USD at the parallel rate of 1,440 ARS/USD). The government continues to phase out remaining subsidies under the IMF reform agreement. Provincial tariffs vary significantly — Mendoza and Córdoba tend to have higher rates than Buenos Aires, making solar even more attractive in those regions. CAMMESA (Compañía Administradora del Mercado Mayorista Eléctrico) sets the wholesale price used for net billing credits.',
      he: 'נכון לפברואר 2026, עלויות חשמל למגורים בבואנוס איירס ממוצעות ב-80-150 ARS לקוט"ש בהתאם לבלוק צריכה (כ-$0.06-0.10 דולר בשער מקביל של 1,440 ARS/USD). הממשלה ממשיכה לבטל סובסידיות נותרות במסגרת הסכם הרפורמה עם IMF. תעריפי פרובינציות משתנים משמעותית — מנדוסה וקורדובה נוטות לתעריפים גבוהים יותר מבואנוס איירס, מה שהופך סולארי לאטרקטיבי אף יותר באזורים אלה. CAMMESA (Compañía Administradora del Mercado Mayorista Eléctrico) קובעת את המחיר הסיטונאי המשמש לזיכויי חיוב נטו.',
    },
  },
  {
    id: 'financing-options',
    title: { en: 'Financing Solar Projects', he: 'מימון פרויקטים סולאריים' },
    category: 'economics',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
    icon: 'Landmark',
    summary: {
      en: 'Explore cash purchase, bank loans, leasing, and government incentive programs.',
      he: 'חקרו רכישה במזומן, הלוואות בנקאיות, ליסינג ותוכניות תמריצים ממשלתיות.',
    },
    content: {
      en: [
        'The most straightforward way to finance a solar system is a cash purchase. You pay the full cost upfront and immediately start saving on electricity bills. With payback periods of 3-5 years in Argentina and system lifetimes of 25+ years, cash buyers enjoy 20+ years of essentially free electricity. However, not everyone has $5,000-15,000 USD available for a residential system or $50,000+ for commercial installations.',
        'Bank loans and credit lines are increasingly available for solar in Argentina. Several banks (Banco Nación, Banco Provincia, BICE) offer green credit lines with preferential rates for renewable energy projects. Loan terms typically range from 3-7 years. The key is to structure the loan so that monthly payments are less than the electricity savings — this way, the system pays for itself from day one. Watch for peso-denominated loans in an inflationary environment — real costs may be lower than expected if inflation outpaces the interest rate.',
        'Leasing and Power Purchase Agreements (PPAs) are emerging in Argentina\'s commercial sector. Under a PPA, a third-party company installs and owns the solar system on your roof, and you buy the electricity at a rate lower than the utility tariff. You get immediate savings with zero upfront cost, but the savings percentage is smaller than with ownership. Government grants and tax incentives at the provincial level can further reduce costs — check with your local energy authority for available programs.',
      ],
      he: [
        'הדרך הפשוטה ביותר לממן מערכת סולארית היא רכישה במזומן. משלמים את העלות המלאה מראש ומתחילים מיד לחסוך בחשבונות חשמל. עם תקופות החזר של 3-5 שנים בארגנטינה ואורך חיי מערכת של 25+ שנים, רוכשים במזומן נהנים מ-20+ שנים של חשמל חינמי למעשה. עם זאת, לא לכולם יש $5,000-15,000 דולר זמינים למערכת ביתית או $50,000+ להתקנות מסחריות.',
        'הלוואות בנקאיות וקווי אשראי הולכים ונעשים זמינים יותר לסולארי בארגנטינה. מספר בנקים (Banco Nación, Banco Provincia, BICE) מציעים קווי אשראי ירוקים עם ריביות מועדפות לפרויקטי אנרגיה מתחדשת. תנאי הלוואה נעים בדרך כלל בין 3-7 שנים. המפתח הוא לבנות את ההלוואה כך שהתשלומים החודשיים נמוכים מחיסכון החשמל — כך המערכת משלמת את עצמה מהיום הראשון. שימו לב להלוואות נקובות בפזו בסביבה אינפלציונית — עלויות ריאליות עשויות להיות נמוכות מהצפוי אם האינפלציה עולה על שיעור הריבית.',
        'ליסינג והסכמי רכישת חשמל (PPA) צצים במגזר המסחרי הארגנטינאי. תחת PPA, חברה צד שלישי מתקינה ומחזיקה את המערכת הסולארית על הגג שלכם, ואתם קונים את החשמל בתעריף נמוך מתעריף חברת החשמל. מקבלים חיסכון מיידי ללא עלות מראש, אך אחוז החיסכון קטן יותר מאשר עם בעלות. מענקים ממשלתיים ותמריצי מס ברמה הפרובינציאלית יכולים להפחית עלויות עוד יותר — בדקו עם רשות האנרגיה המקומית לגבי תוכניות זמינות.',
      ],
    },
    keyPoints: {
      en: [
        'Cash purchase offers the best lifetime returns — 20+ years of free electricity after 3-5 year payback',
        'Green credit lines from Argentine banks (Banco Nación, BICE) offer preferential rates for solar projects',
        'Structure loans so monthly savings exceed monthly payments for positive cash flow from day one',
        'PPAs allow commercial users to go solar with zero upfront investment at reduced electricity rates',
        'Provincial governments may offer grants, tax breaks, or low-interest financing — check locally',
      ],
      he: [
        'רכישה במזומן מציעה את התשואה הטובה ביותר לאורך חיי המערכת — 20+ שנים של חשמל חינמי אחרי החזר של 3-5 שנים',
        'קווי אשראי ירוקים מבנקים ארגנטינאיים (Banco Nación, BICE) מציעים ריביות מועדפות לפרויקטים סולאריים',
        'בנו הלוואות כך שהחיסכון החודשי עולה על התשלומים החודשיים לתזרים חיובי מהיום הראשון',
        'PPA מאפשרים למשתמשים מסחריים לעבור לסולארי ללא השקעה מראש בתעריפי חשמל מופחתים',
        'ממשלות פרובינציאליות עשויות להציע מענקים, הטבות מס או מימון בריבית נמוכה — בדקו מקומית',
      ],
    },
    practicalTips: {
      en: [
        'If paying cash in Argentina, consider purchasing in USD or dollar-linked terms to protect against peso devaluation',
        'Compare at least 3 bank offers — interest rates, terms, and collateral requirements vary significantly between institutions',
        'For commercial projects over 50 kWp, explore BICE (Banco de Inversión y Comercio Exterior) financing specifically designed for renewable energy',
        'Ask your installer about payment plans — many offer 6-12 month installment options that bridge the gap until savings accumulate',
      ],
      he: [
        'אם משלמים במזומן בארגנטינה, שקלו רכישה בדולרים או בתנאים צמודי דולר להגנה מפני פיחות הפזו',
        'השוו לפחות 3 הצעות בנקאיות — ריביות, תנאים ודרישות ביטחונות משתנים משמעותית בין מוסדות',
        'לפרויקטים מסחריים מעל 50 kWp, חקרו מימון BICE (Banco de Inversión y Comercio Exterior) שתוכנן במיוחד לאנרגיה מתחדשת',
        'שאלו את המתקין על תוכניות תשלום — רבים מציעים אופציות תשלומים של 6-12 חודשים שמגשרים על הפער עד שהחיסכון מצטבר',
      ],
    },
    argentinaContext: {
      en: 'Banco Nación offers a "Línea de Crédito para Energías Renovables" with up to 7-year terms for solar installations. BICE provides project finance for commercial and industrial solar above 50 kWp. Several provinces (San Juan, Mendoza, Salta) offer additional provincial incentives including property tax exemptions for solar installations. The national government\'s MATER (Mercado a Término de Energías Renovables) program enables large commercial consumers to purchase renewable energy directly from generators at competitive rates.',
      he: 'Banco Nación מציע "קו אשראי לאנרגיות מתחדשות" עם תנאים של עד 7 שנים להתקנות סולאריות. BICE מספק מימון פרויקטים לסולארי מסחרי ותעשייתי מעל 50 kWp. מספר פרובינציות (סן חואן, מנדוסה, סלטה) מציעות תמריצים פרובינציאליים נוספים כולל פטור מארנונה להתקנות סולאריות. תוכנית MATER (Mercado a Término de Energías Renovables) של הממשלה הלאומית מאפשרת לצרכנים מסחריים גדולים לרכוש אנרגיה מתחדשת ישירות ממפיקים במחירים תחרותיים.',
    },
  },
  {
    id: 'ley-27424',
    title: { en: 'Ley 27.424 — Argentina\'s Solar Law', he: 'חוק 27.424 — חוק הסולארי של ארגנטינה' },
    category: 'regulatory',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    icon: 'Scale',
    summary: {
      en: 'Understand the Distributed Generation law, prosumer rights, and provincial adherence.',
      he: 'הבינו את חוק הייצור המבוזר, זכויות הפרוסיומר והצטרפות פרובינציאלית.',
    },
    content: {
      en: [
        'Ley 27.424, enacted in December 2017, is Argentina\'s foundational law for distributed renewable energy generation. It establishes the legal framework for "prosumers" — consumers who also produce electricity — to connect solar systems to the grid and receive compensation for exported energy. The law applies to systems up to 300 kW and covers solar, wind, biomass, biogas, and small hydro. It created the legal right to self-generate, inject surplus into the grid, and receive credits on your electricity bill.',
        'The law operates on a net billing basis: energy injected into the grid is valued at the wholesale energy cost (costo de la energía) set by CAMMESA, not the full retail tariff. While this is less favorable than full net metering, the dramatic tariff increases since 2024 have made even net billing highly profitable. The law also prohibits utilities from discriminating against prosumers and guarantees connection within a defined timeline after application approval.',
        'Implementation requires each province to formally adhere ("adherir") to the national law and establish local regulations. As of 2026, most major provinces have adhered, though implementation quality varies. Buenos Aires Province, Ciudad Autónoma de Buenos Aires (CABA), Mendoza, San Juan, Córdoba, and Santa Fe have the most mature regulatory frameworks. Some provinces have added their own incentives on top of the national law, such as property tax exemptions or accelerated permitting.',
      ],
      he: [
        'חוק 27.424, שנחקק בדצמבר 2017, הוא החוק הבסיסי של ארגנטינה לייצור אנרגיה מתחדשת מבוזרת. הוא מקים את המסגרת החוקית ל"פרוסיומרים" — צרכנים שגם מייצרים חשמל — לחבר מערכות סולאריות לרשת ולקבל פיצוי על אנרגיה מיוצאת. החוק חל על מערכות עד 300 kW ומכסה סולארי, רוח, ביומסה, ביוגז ומיני-הידרו. הוא יצר את הזכות החוקית לייצור עצמי, הזרקת עודפים לרשת, וקבלת זיכויים בחשבון החשמל.',
        'החוק פועל על בסיס חיוב נטו: אנרגיה שמוזרקת לרשת מוערכת בעלות האנרגיה הסיטונאית (costo de la energía) שנקבעת על ידי CAMMESA, ולא בתעריף הקמעונאי המלא. בעוד שזה פחות נוח ממדידה נטו מלאה, עליות התעריפים הדרמטיות מאז 2024 הפכו גם חיוב נטו לרווחי מאוד. החוק גם אוסר על חברות חשמל להפלות פרוסיומרים ומבטיח חיבור בתוך לוח זמנים מוגדר לאחר אישור הבקשה.',
        'יישום דורש מכל פרובינציה להצטרף רשמית ("adherir") לחוק הלאומי ולקבוע רגולציה מקומית. נכון ל-2026, רוב הפרובינציות הגדולות הצטרפו, אם כי איכות היישום משתנה. Buenos Aires Province, Ciudad Autónoma de Buenos Aires (CABA), מנדוסה, סן חואן, קורדובה וסנטה פה מחזיקות את המסגרות הרגולטוריות הבשלות ביותר. חלק מהפרובינציות הוסיפו תמריצים משלהן מעל החוק הלאומי, כגון פטור מארנונה או הליכי אישור מואצים.',
      ],
    },
    keyPoints: {
      en: [
        'Ley 27.424 establishes the legal right to generate solar energy, export to the grid, and receive bill credits',
        'The law covers systems up to 300 kW and applies to solar, wind, biomass, biogas, and small hydro',
        'Compensation is net billing at wholesale energy cost (costo de la energía), not full retail rate',
        'Each province must formally adhere to the law and create local implementation regulations',
        'Utilities cannot discriminate against prosumers and must connect approved systems within defined timelines',
      ],
      he: [
        'חוק 27.424 מקים את הזכות החוקית לייצר אנרגיה סולארית, לייצא לרשת ולקבל זיכויי חשבון',
        'החוק מכסה מערכות עד 300 kW וחל על סולארי, רוח, ביומסה, ביוגז ומיני-הידרו',
        'הפיצוי הוא חיוב נטו בעלות אנרגיה סיטונאית (costo de la energía), לא בתעריף קמעונאי מלא',
        'כל פרובינציה חייבת להצטרף רשמית לחוק וליצור רגולציה מקומית ליישום',
        'חברות חשמל לא יכולות להפלות פרוסיומרים וחייבות לחבר מערכות מאושרות בתוך לוחות זמנים מוגדרים',
      ],
    },
    practicalTips: {
      en: [
        'Before starting, verify that your province has formally adhered to Ley 27.424 — contact your provincial energy secretary',
        'Register as a prosumer through your local utility company\'s website or office — this is the mandatory first step',
        'Keep copies of all submitted documentation including the connection request, single-line diagram, and inverter certifications',
        'Join local prosumer groups on social media (Facebook groups like "Generación Distribuida Argentina") for practical advice and updates',
      ],
      he: [
        'לפני שמתחילים, ודאו שהפרובינציה שלכם הצטרפה רשמית לחוק 27.424 — פנו למזכירות האנרגיה הפרובינציאלית',
        'הירשמו כפרוסיומר דרך אתר או משרד חברת החשמל המקומית — זה הצעד החובה הראשון',
        'שמרו עותקים של כל התיעוד שהוגש כולל בקשת חיבור, תרשים חד-קווי ותעודות אינוורטר',
        'הצטרפו לקבוצות פרוסיומרים מקומיות ברשתות חברתיות (קבוצות פייסבוק כמו "Generación Distribuida Argentina") לעצות מעשיות ועדכונים',
      ],
    },
    argentinaContext: {
      en: 'As of 2026, the ENRE (Ente Nacional Regulador de la Electricidad) reports approximately 2,900 registered prosumers with a combined capacity of 78 MW nationwide. The majority are in Buenos Aires Province, CABA, and Mendoza. The registration process varies by distributor but generally requires: a connection request form, electrical diagram signed by a licensed electrician, inverter compliance certificates, and proof of property ownership. Processing times range from 2-8 weeks depending on the jurisdiction.',
      he: 'נכון ל-2026, ENRE (הרגולטור הלאומי לחשמל) מדווח על כ-2,900 פרוסיומרים רשומים עם הספק משולב של 78 MW ברחבי המדינה. הרוב נמצאים ב-Buenos Aires Province, CABA ומנדוסה. תהליך הרישום משתנה לפי מפיץ אך בדרך כלל דורש: טופס בקשת חיבור, תרשים חשמלי חתום על ידי חשמלאי מורשה, תעודות תאימות אינוורטר, והוכחת בעלות נכס. זמני טיפול נעים בין 2-8 שבועות בהתאם לתחום השיפוט.',
    },
  },
  {
    id: 'permits-grid-connection',
    title: { en: 'Permits & Grid Connection', he: 'היתרים וחיבור לרשת' },
    category: 'regulatory',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    icon: 'FileCheck',
    summary: {
      en: 'Navigate the permitting process, required documents, and grid connection timeline.',
      he: 'נווטו בתהליך ההיתרים, מסמכים נדרשים ולוח זמנים לחיבור לרשת.',
    },
    content: {
      en: [
        'Installing a grid-connected solar system in Argentina requires navigating a multi-step permitting process. The process begins with a formal connection request to your electricity distributor (e.g., EDENOR, EDESUR, EPEC, EMESA). This request must include a single-line electrical diagram prepared by a licensed electrician (matriculado), technical specifications of the panels and inverter, proof of property ownership or authorization, and the applicant\'s tax identification (CUIT/CUIL).',
        'After submitting the connection request, the distributor reviews the technical feasibility — primarily checking that the local transformer and grid segment can handle the additional generation capacity. For residential systems under 10 kWp, this is usually straightforward. Larger commercial systems may require grid impact studies. Once technically approved, you receive authorization to proceed with installation. After installation, the distributor inspects the system, installs a bidirectional meter, and activates the connection.',
        'The entire process from application to activation typically takes 4-12 weeks, though this varies significantly by jurisdiction and distributor efficiency. Common causes of delay include incomplete documentation, transformer capacity limitations, and bureaucratic backlogs. Working with an experienced installer who handles the paperwork is highly recommended — they know the specific requirements and contacts at each distributor.',
      ],
      he: [
        'התקנת מערכת סולארית מחוברת לרשת בארגנטינה דורשת ניווט בתהליך היתרים רב-שלבי. התהליך מתחיל עם בקשת חיבור רשמית למפיץ החשמל שלכם (למשל, EDENOR, EDESUR, EPEC, EMESA). בקשה זו חייבת לכלול תרשים חשמלי חד-קווי שהוכן על ידי חשמלאי מורשה (matriculado), מפרטים טכניים של הפאנלים והאינוורטר, הוכחת בעלות נכס או הרשאה, וזיהוי מס של המבקש (CUIT/CUIL).',
        'לאחר הגשת בקשת החיבור, המפיץ בוחן את ההיתכנות הטכנית — בעיקר בודק שהשנאי המקומי ומקטע הרשת יכולים להתמודד עם קיבולת הייצור הנוספת. למערכות מגורים מתחת ל-10 kWp, זה בדרך כלל פשוט. מערכות מסחריות גדולות יותר עשויות לדרוש מחקרי השפעה על הרשת. לאחר אישור טכני, מקבלים הרשאה להמשיך בהתקנה. לאחר ההתקנה, המפיץ בודק את המערכת, מתקין מונה דו-כיווני ומפעיל את החיבור.',
        'התהליך כולו מהגשת בקשה ועד הפעלה לוקח בדרך כלל 4-12 שבועות, אם כי זה משתנה משמעותית לפי תחום שיפוט ויעילות המפיץ. סיבות נפוצות לעיכוב כוללות תיעוד חסר, מגבלות קיבולת שנאי ופיגורים בירוקרטיים. עבודה עם מתקין מנוסה שמטפל בניירת מומלצת מאוד — הם מכירים את הדרישות הספציפיות ואנשי הקשר בכל מפיץ.',
      ],
    },
    keyPoints: {
      en: [
        'A licensed electrician (matriculado) must prepare the single-line diagram and sign off on the installation',
        'The distributor must verify transformer capacity before approving your connection — this can be a bottleneck',
        'Required documents: connection request, electrical diagram, equipment specs, property proof, tax ID (CUIT/CUIL)',
        'Timeline from application to activation: 4-12 weeks depending on jurisdiction and system size',
        'A bidirectional meter is installed by the distributor at their cost as part of the connection process',
      ],
      he: [
        'חשמלאי מורשה (matriculado) חייב להכין את התרשים החד-קווי ולחתום על ההתקנה',
        'המפיץ חייב לאמת קיבולת שנאי לפני אישור החיבור — זה יכול להיות צוואר בקבוק',
        'מסמכים נדרשים: בקשת חיבור, תרשים חשמלי, מפרטי ציוד, הוכחת בעלות, מספר מס (CUIT/CUIL)',
        'לוח זמנים מהגשה ועד הפעלה: 4-12 שבועות בהתאם לתחום שיפוט וגודל מערכת',
        'מונה דו-כיווני מותקן על ידי המפיץ על חשבונו כחלק מתהליך החיבור',
      ],
    },
    practicalTips: {
      en: [
        'Start the permitting process before purchasing equipment — approval can take weeks and requirements may affect your system design',
        'Keep a checklist of all required documents and submit everything at once to avoid back-and-forth delays',
        'Ask your installer for references from previous projects with your specific distributor — they can share timeline expectations',
        'For commercial projects, engage a licensed electrical engineer early to handle grid impact studies if required by the distributor',
      ],
      he: [
        'התחילו את תהליך ההיתרים לפני רכישת ציוד — אישור יכול לקחת שבועות והדרישות עשויות להשפיע על תכנון המערכת',
        'שמרו רשימת בדיקה של כל המסמכים הנדרשים והגישו הכול בבת אחת כדי להימנע מעיכובים הלוך ושוב',
        'בקשו מהמתקין הפניות מפרויקטים קודמים עם המפיץ הספציפי שלכם — הם יכולים לשתף ציפיות לגבי לוח זמנים',
        'לפרויקטים מסחריים, הפעילו מהנדס חשמל מורשה מוקדם כדי לטפל במחקרי השפעה על הרשת אם נדרש על ידי המפיץ',
      ],
    },
    argentinaContext: {
      en: 'EDENOR and EDESUR in Buenos Aires have dedicated distributed generation departments with online application portals. EPEC in Córdoba and EMESA in Mendoza have streamlined processes for residential systems. In less developed provinces, the process may be slower due to limited staff familiarity with distributed generation. The Argentine College of Electrical Engineers (COPIME or equivalent provincial body) maintains the registry of licensed electricians authorized to sign off on solar installations. Always verify your electrician\'s active registration.',
      he: 'ל-EDENOR ו-EDESUR בבואנוס איירס יש מחלקות ייצור מבוזר ייעודיות עם פורטלי הגשה מקוונים. EPEC בקורדובה ו-EMESA במנדוסה מחזיקות תהליכים יעילים למערכות מגורים. בפרובינציות פחות מפותחות, התהליך עשוי להיות איטי יותר בגלל היכרות מוגבלת של הצוות עם ייצור מבוזר. לשכת המהנדסים החשמלאים הארגנטינאית (COPIME או גוף פרובינציאלי מקביל) מנהלת את רישום החשמלאים המורשים לחתום על התקנות סולאריות. תמיד אמתו את הרישום הפעיל של החשמלאי.',
    },
  },
  {
    id: 'site-assessment',
    title: { en: 'Site Assessment & Shading Analysis', he: 'סקר אתר וניתוח הצללה' },
    category: 'operations',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    icon: 'Search',
    summary: {
      en: 'Conduct thorough roof inspections, shading analysis, and structural assessments.',
      he: 'בצעו סקירות גג יסודיות, ניתוח הצללה והערכות מבניות.',
    },
    content: {
      en: [
        'A proper site assessment is the foundation of a successful solar installation. It begins with a physical roof inspection covering structural integrity, material type (tile, metal, concrete, membrane), age and condition, and load-bearing capacity. Solar panels add 10-15 kg/m² to the roof load — most modern roofs can handle this, but older structures may need reinforcement. Measure all usable roof areas, noting dimensions, orientation (azimuth), and tilt angle. In the southern hemisphere, north-facing surfaces receive the most sunlight.',
        'Shading analysis is critical because even partial shading on a single panel can dramatically reduce output for the entire string (with string inverters). Use tools like a Solar Pathfinder, SunEye analyzer, or free apps like Sun Surveyor to map shade patterns throughout the year. Common shading sources include neighboring buildings, trees (consider growth over 25 years), chimneys, water tanks, antennas, and overhead power lines. Morning and afternoon shading is less impactful than midday shading when production peaks.',
        'Beyond the roof, assess the electrical infrastructure: the main panel capacity, available breaker positions, distance from the roof to the meter (affects cable sizing and voltage drop), and the condition of the existing grounding system. Document everything with photographs, measurements, and GPS coordinates. This data feeds into the system design software (PVsyst, Helioscope, or similar) to generate accurate production estimates and optimal panel layout.',
      ],
      he: [
        'סקר אתר נכון הוא הבסיס להתקנה סולארית מוצלחת. הוא מתחיל עם סקירת גג פיזית המכסה שלמות מבנית, סוג חומר (רעפים, פח, בטון, ממברנה), גיל ומצב, וכושר נשיאה. פאנלים סולאריים מוסיפים 10-15 ק"ג/מ"ר לעומס הגג — רוב הגגות המודרניים מסוגלים להתמודד עם זה, אך מבנים ישנים יותר עשויים לדרוש חיזוק. מדדו את כל שטחי הגג הניתנים לשימוש, תוך ציון ממדים, כיוון (אזימוט) וזווית הטייה. בחצי הכדור הדרומי, משטחים הפונים צפונה מקבלים את מירב אור השמש.',
        'ניתוח הצללה הוא קריטי כי אפילו הצללה חלקית על פאנל בודד יכולה להפחית דרמטית את התפוקה של כל השרשרת (עם אינוורטרים מרכזיים). השתמשו בכלים כמו Solar Pathfinder, מנתח SunEye, או אפליקציות חינמיות כמו Sun Surveyor למיפוי דפוסי צל לאורך השנה. מקורות הצללה נפוצים כוללים בניינים שכנים, עצים (שקלו גדילה על פני 25 שנה), ארובות, מיכלי מים, אנטנות וקווי חשמל עיליים. הצללה בבוקר ואחר הצהריים פחות משפיעה מהצללה בצהריים כשהייצור בשיא.',
        'מעבר לגג, העריכו את התשתית החשמלית: קיבולת הלוח הראשי, מקומות מפסק זמינים, מרחק מהגג למונה (משפיע על גודל כבלים ונפילת מתח), ומצב מערכת ההארקה הקיימת. תעדו הכול בתצלומים, מדידות ונקודות GPS. נתונים אלה מוזנים לתוכנת תכנון מערכת (PVsyst, Helioscope או דומה) ליצירת הערכות ייצור מדויקות ופריסת פאנלים מיטבית.',
      ],
    },
    keyPoints: {
      en: [
        'Structural assessment must confirm the roof can support 10-15 kg/m² additional load from panels and mounting',
        'In the southern hemisphere, north-facing roof surfaces provide optimal solar exposure',
        'Shading from even one object can reduce entire string output — map shadows across all seasons',
        'Assess electrical panel capacity, breaker space, cable run length, and grounding before designing the system',
        'Use professional tools (Solar Pathfinder, SunEye, PVsyst) for accurate shading and production analysis',
      ],
      he: [
        'הערכה מבנית חייבת לאשר שהגג יכול לתמוך ב-10-15 ק"ג/מ"ר עומס נוסף מפאנלים והרכבה',
        'בחצי הכדור הדרומי, משטחי גג הפונים צפונה מספקים חשיפה סולארית מיטבית',
        'הצללה אפילו מגורם אחד יכולה להפחית את תפוקת כל השרשרת — מפו צללים לאורך כל העונות',
        'העריכו קיבולת לוח חשמל, מקום למפסקים, אורך כבילה והארקה לפני תכנון המערכת',
        'השתמשו בכלים מקצועיים (Solar Pathfinder, SunEye, PVsyst) לניתוח הצללה וייצור מדויק',
      ],
    },
    practicalTips: {
      en: [
        'Visit the site at solar noon (around 13:00 in Argentina) to observe the worst-case shading scenario for midday production',
        'Take photos from multiple angles and create a simple sketch with measurements — this saves time during the design phase',
        'Check the roof warranty before installation — drilling into some membrane or metal roofs may void the waterproofing guarantee',
        'For flat roofs, plan for minimum row spacing between tilted panel rows to avoid self-shading — typically 1.5-2x the panel height',
      ],
      he: [
        'בקרו באתר בצהריים סולאריים (סביב 13:00 בארגנטינה) לצפייה בתרחיש ההצללה הגרוע ביותר לייצור צהריים',
        'צלמו ממספר זוויות וצרו סקיצה פשוטה עם מידות — זה חוסך זמן בשלב התכנון',
        'בדקו את אחריות הגג לפני ההתקנה — קידוח בגגות ממברנה או פח מסוימים עשוי לבטל את אחריות האיטום',
        'לגגות שטוחים, תכננו מרווח מינימלי בין שורות פאנלים מוטים כדי למנוע הצללה עצמית — בדרך כלל 1.5-2 פי גובה הפאנל',
      ],
    },
    argentinaContext: {
      en: 'Argentine roof construction varies significantly by region. In Buenos Aires, most residential roofs are concrete ("losa") or tile, which provide excellent structural support for solar panels. In the northern provinces, lighter metal sheet ("chapa") roofs are common and may require additional mounting considerations. The optimal panel tilt angle varies from about 22° in Salta (22°S latitude) to 38° in Buenos Aires (34°S) and 52° in Ushuaia (54°S). Many Argentine homes have flat concrete roofs (terraza) ideal for adjustable tilt mounting systems.',
      he: 'בניית גגות בארגנטינה משתנה משמעותית לפי אזור. בבואנוס איירס, רוב גגות המגורים הם בטון ("losa") או רעפים, שמספקים תמיכה מבנית מצוינת לפאנלים סולאריים. בפרובינציות הצפוניות, גגות פח קלים ("chapa") נפוצים ועשויים לדרוש שיקולי הרכבה נוספים. זווית הטייה מיטבית של פאנלים משתנה מכ-22° בסלטה (קו רוחב 22°S) ל-38° בבואנוס איירס (34°S) ו-52° באושואייה (54°S). לבתים ארגנטינאיים רבים גגות בטון שטוחים (terraza) אידיאליים למערכות הרכבה בזווית מתכווננת.',
    },
  },
  {
    id: 'installation-process',
    title: { en: 'Installation & Commissioning', he: 'התקנה ותפעול ראשוני' },
    category: 'operations',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    icon: 'Wrench',
    summary: {
      en: 'Follow the step-by-step installation process from delivery to commissioning and handover.',
      he: 'עקבו אחר תהליך ההתקנה שלב אחר שלב מאספקה ועד תפעול ראשוני ומסירה.',
    },
    content: {
      en: [
        'A professional solar installation follows a structured process. Day 1 typically involves mounting structure installation: laying out rails or brackets on the roof according to the design plan, drilling anchor points (ensuring waterproof sealing), and leveling the mounting system. Safety equipment (harnesses, roof anchors) is mandatory for any work above 2 meters. The mounting structure must be perfectly aligned to ensure panels sit flush and can withstand wind loads.',
        'Day 2 focuses on panel placement and electrical work. Panels are carried to the roof (never dragged — this damages cells), secured to the mounting rails with clamps, and connected in series strings according to the string diagram. DC cabling is routed through conduit to the inverter location, where the inverter is wall-mounted in a ventilated, shaded area (inverters lose efficiency in heat). AC wiring connects the inverter output to the main electrical panel through a dedicated circuit breaker. Grounding connections are made to all metal components.',
        'Commissioning is the final and most critical phase. The installer performs a systematic check: visual inspection of all connections, DC voltage and current measurements on each string, insulation resistance testing, grounding continuity verification, and inverter configuration (grid frequency, voltage limits, power factor). Once everything checks out, the inverter is powered on and the system begins producing. The installer should provide a commissioning report, as-built drawings, equipment manuals, warranty certificates, and user training on the monitoring system.',
      ],
      he: [
        'התקנה סולארית מקצועית עוקבת אחר תהליך מובנה. יום 1 כולל בדרך כלל התקנת מבנה ההרכבה: פריסת מסילות או תושבות על הגג לפי תוכנית התכנון, קידוח נקודות עיגון (הבטחת איטום נגד מים), ופילוס מערכת ההרכבה. ציוד בטיחות (רתמות, עוגני גג) חובה לכל עבודה מעל 2 מטר. מבנה ההרכבה חייב להיות מיושר בצורה מושלמת כדי להבטיח שהפאנלים ישבו בצורה חלקה ויוכלו לעמוד בעומסי רוח.',
        'יום 2 מתמקד בהנחת פאנלים ועבודה חשמלית. פאנלים מועלים לגג (לעולם לא נגררים — זה פוגע בתאים), מאובטחים למסילות ההרכבה עם מהדקים, ומחוברים בשרשרות סדרתיות לפי תרשים השרשרות. כבילת DC מנותבת דרך צנרת למיקום האינוורטר, שם האינוורטר מותקן על קיר באזור מאוורר ומוצל (אינוורטרים מאבדים נצילות בחום). חיווט AC מחבר את פלט האינוורטר ללוח החשמל הראשי דרך מפסק זרם ייעודי. חיבורי הארקה נעשים לכל הרכיבים המתכתיים.',
        'תפעול ראשוני (commissioning) הוא השלב האחרון והקריטי ביותר. המתקין מבצע בדיקה שיטתית: סקירה חזותית של כל החיבורים, מדידות מתח וזרם DC בכל שרשרת, בדיקת עמידות בידוד, אימות רציפות הארקה, ותצורת אינוורטר (תדר רשת, גבולות מתח, גורם הספק). ברגע שהכול תקין, האינוורטר מופעל והמערכת מתחילה לייצר. המתקין צריך לספק דוח תפעול ראשוני, שרטוטי as-built, מדריכי ציוד, תעודות אחריות והדרכת משתמש במערכת הניטור.',
      ],
    },
    keyPoints: {
      en: [
        'Professional installation typically takes 1-3 days for residential systems and 1-4 weeks for commercial',
        'Mounting alignment and waterproof sealing at anchor points are critical for long-term roof integrity',
        'All DC wiring must be run in UV-resistant conduit and properly labeled with polarity markings',
        'Commissioning includes voltage/current checks, insulation testing, grounding verification, and inverter setup',
        'Demand a complete handover package: commissioning report, as-built drawings, manuals, warranties, and monitoring training',
      ],
      he: [
        'התקנה מקצועית לוקחת בדרך כלל 1-3 ימים למערכות מגורים ו-1-4 שבועות למסחריות',
        'יישור הרכבה ואיטום עמיד למים בנקודות עיגון קריטיים לשלמות הגג לטווח ארוך',
        'כל חיווט DC חייב לעבור בצנרת עמידה ב-UV ולהיות מסומן כראוי עם סימני קוטביות',
        'תפעול ראשוני כולל בדיקות מתח/זרם, בדיקת בידוד, אימות הארקה והגדרת אינוורטר',
        'דרשו חבילת מסירה מלאה: דוח תפעול ראשוני, שרטוטי as-built, מדריכים, אחריות והדרכת ניטור',
      ],
    },
    practicalTips: {
      en: [
        'Be present during installation if possible — ask questions and take photos of every stage for your records',
        'Verify that the installer uses torque wrenches for MC4 connectors — hand-tightening leads to loose connections and potential arc faults',
        'Ensure the inverter is mounted in shade with adequate ventilation — direct sun exposure reduces efficiency and shortens lifespan',
        'After commissioning, monitor the system daily for the first two weeks to establish a production baseline and catch early issues',
      ],
      he: [
        'היו נוכחים במהלך ההתקנה אם אפשר — שאלו שאלות וצלמו כל שלב לתיעוד שלכם',
        'ודאו שהמתקין משתמש במפתחות מומנט למחברי MC4 — הידוק ידני מוביל לחיבורים רופפים וקשת חשמלית אפשרית',
        'ודאו שהאינוורטר מותקן בצל עם אוורור מספק — חשיפה ישירה לשמש מפחיתה נצילות ומקצרת אורך חיים',
        'לאחר תפעול ראשוני, עקבו אחר המערכת יומיים במשך השבועיים הראשונים לקביעת קו בסיס ייצור ותפיסת בעיות מוקדמות',
      ],
    },
    argentinaContext: {
      en: 'In Argentina, all solar installations must be supervised by a licensed electrician registered with the local professional council (Colegio de Técnicos or COPIME). Installation labor costs range from $300-600 USD per kWp, which is included in the typical total system price of $1,400-1,750 per kWp. Most reputable Argentine installers offer 2-5 year workmanship warranties covering installation defects. The installer should handle the post-installation utility inspection and bidirectional meter swap as part of their service.',
      he: 'בארגנטינה, כל ההתקנות הסולאריות חייבות להיות מפוקחות על ידי חשמלאי מורשה הרשום במועצה המקצועית המקומית (Colegio de Técnicos או COPIME). עלויות עבודת התקנה נעות בין $300-600 דולר ל-kWp, שנכללות במחיר המערכת הכולל הטיפוסי של $1,400-1,750 ל-kWp. רוב המתקינים הארגנטינאיים המכובדים מציעים אחריות עבודה של 2-5 שנים המכסה פגמי התקנה. המתקין צריך לטפל בסקירת חברת החשמל לאחר ההתקנה ובהחלפת המונה הדו-כיווני כחלק מהשירות שלו.',
    },
  },
];
